export const filters = [
  { value: 'all', label: 'All' },
  { value: 'spices', label: 'Spices & Herbs' },
  { value: 'pantry', label: 'Pantry Staples' },
  { value: 'oils', label: 'Oils & Vinegars' },
];

export const products = [
  {
    id: 'dried-oregano',
    title: 'Dried Oregano',
    price: 'Rp 27.000',
    stock: 80,
    category: 'spices',
    meta: '30 g • Aromatic Mediterranean herb',
    img: '/assets/shop/Ingredients/Dried_Oregano.jpg',
    alt: 'Dried Oregano',
    details: 'Perfect for pizza, pasta, and salads. Store in an airtight container away from heat and light.',
  },
  {
    id: 'sea-salt-fine',
    title: 'Sea Salt — Fine',
    price: 'Rp 37.500',
    stock: 120,
    category: 'pantry',
    meta: '500 g • Natural sea salt',
    img: '/assets/shop/Ingredients/Sea_Salt.jpg',
    alt: 'Sea Salt',
    details: 'Fine-grain sea salt with clean mineral flavor. Great for seasoning and finishing. Keep dry.',
  },
  {
    id: 'olive-oil-extra-virgin',
    title: 'Olive Oil — Extra Virgin',
    price: 'Rp 112.500',
    stock: 24,
    category: 'oils',
    meta: '250 ml • Premium cold-pressed',
    img: '/assets/shop/Ingredients/Olive_Oil_Virgin.png',
    alt: 'Olive Oil',
    details:
      'Cold-pressed extra virgin olive oil for dressings, drizzling and low‑heat cooking. Store in a cool, dark place.',
  },
  {
    id: 'black-pepper-ground',
    title: 'Black Pepper — Ground',
    price: 'Rp 18.000',
    stock: 150,
    category: 'spices',
    meta: '50 g • Aromatic spice',
    img: '/assets/shop/Ingredients/Black_Pepper_Ground.jpg',
    alt: 'Black Pepper',
    details: 'Freshly ground black pepper for robust seasoning. Keep sealed for best aroma.',
  },
  {
    id: 'cumin-powder',
    title: 'Cumin Powder',
    price: 'Rp 22.500',
    stock: 90,
    category: 'spices',
    meta: '40 g • Warm, earthy',
    img: '/assets/shop/Ingredients/Cumin_Powder.jpg',
    alt: 'Cumin Powder',
    details: 'Warm, earthy cumin powder — essential for curries, stews and spice blends. Store in a cool dry place.',
  },
  {
    id: 'brown-sugar',
    title: 'Brown Sugar',
    price: 'Rp 48.000',
    stock: 70,
    category: 'pantry',
    meta: '500 g • Soft & moist',
    img: '/assets/shop/Ingredients/Brown_Sugar.jpg',
    alt: 'Brown Sugar',
    details: 'Soft, moist brown sugar perfect for baking and sauces. Keep airtight to prevent hardening.',
  },
  {
    id: 'canned-tomatoes',
    title: 'Canned Tomatoes',
    price: 'Rp 30.000',
    stock: 110,
    category: 'pantry',
    meta: '400 g • Peeled, diced',
    img: '/assets/shop/Ingredients/Canned_Tomatoes.jpg',
    alt: 'Canned Tomatoes',
    details: 'Peeled and diced tomatoes — great for sauces, soups and stews. Use within a few days after opening.',
  },
  {
    id: 'honey-wildflower',
    title: 'Honey — Wildflower',
    price: 'Rp 67.500',
    stock: 50,
    category: 'pantry',
    meta: '250 g • Natural sweetener',
    img: '/assets/shop/Ingredients/Honey_Wildflower.jpg',
    alt: 'Honey',
    details:
      'Natural wildflower honey. Use as a sweetener or glaze. Store at room temperature; it may crystallize but is still fine.',
  },
  {
    id: 'sesame-oil',
    title: 'Sesame Oil',
    price: 'Rp 57.000',
    stock: 45,
    category: 'oils',
    meta: '150 ml • Toasted aroma',
    img: '/assets/shop/Ingredients/Sesame_Oil.jpg',
    alt: 'Sesame Oil',
    details:
      'Toasted sesame oil with a nutty aroma — use sparingly as a finishing oil for dressings and stir-fries.',
  },
  {
    id: 'balsamic-vinegar',
    title: 'Balsamic Vinegar',
    price: 'Rp 82.500',
    stock: 30,
    category: 'oils',
    meta: '250 ml • Aged',
    img: '/assets/shop/Ingredients/Balsamic_Vinnegar.jpg',
    alt: 'Balsamic Vinegar',
    details: 'Aged balsamic vinegar ideal for salads, glazes and reductions. Store in a cool pantry.',
  },
  {
    id: 'white-vinegar',
    title: 'White Vinegar',
    price: 'Rp 22.000',
    stock: 200,
    category: 'oils',
    meta: '500 ml • Multipurpose',
    img: '/assets/shop/Ingredients/White_Vinnegar.jpg',
    alt: 'White Vinegar',
    details: 'Multipurpose white vinegar — great for pickling, cleaning and cooking. Store sealed at room temperature.',
  },
  {
    id: 'garlic-powder',
    title: 'Garlic Powder',
    price: 'Rp 20.000',
    stock: 140,
    category: 'spices',
    meta: '60 g • Savoury & concentrated',
    img: '/assets/shop/Ingredients/Garlic_Powder.jpg',
    alt: 'Garlic Powder',
    details: 'Savoury, concentrated garlic powder — convenient for rubs and quick seasoning.',
  },
  {
    id: 'smoked-paprika',
    title: 'Smoked Paprika',
    price: 'Rp 28.500',
    stock: 95,
    category: 'spices',
    meta: '45 g • Sweet, smoky',
    img: '/assets/shop/Ingredients/Smoked_Paprika.jpg',
    alt: 'Smoked Paprika',
    details: 'Sweet-smoky paprika for depth in stews, rubs and Spanish dishes. Store tightly sealed.',
  },
  {
    id: 'coconut-milk',
    title: 'Coconut Milk',
    price: 'Rp 33.000',
    stock: 85,
    category: 'pantry',
    meta: '400 ml • Creamy & rich',
    img: '/assets/shop/Ingredients/Coconut_Milk.jpg',
    alt: 'Coconut Milk',
    details:
      'Creamy coconut milk for curries and desserts. Shake or stir well; refrigerate after opening and use quickly.',
  },
  {
    id: 'soy-sauce-light',
    title: 'Soy Sauce — Light',
    price: 'Rp 26.000',
    stock: 160,
    category: 'pantry',
    meta: '300 ml • Umami seasoning',
    img: '/assets/shop/Ingredients/Light_Soy_Sauce.png',
    alt: 'Soy Sauce',
    details:
      'Light soy sauce with a salty, umami flavor — perfect for marinades and seasoning. Store in a cool place.',
  },
  {
    id: 'truffle-oil',
    title: 'Truffle Oil',
    price: 'Rp 145.000',
    stock: 12,
    category: 'oils',
    meta: '100 ml • Gourmet finishing oil',
    img: '/assets/shop/Ingredients/Truffle_Oil.jpg',
    alt: 'Truffle Oil',
    details:
      'Gourmet finishing oil with truffle aroma — use sparingly to finish dishes; do not cook at high heat.',
  },
  {
    id: 'turmeric-powder',
    title: 'Turmeric Powder',
    price: 'Rp 32.000',
    stock: 95,
    category: 'spices',
    meta: '100 g • Earthy, warm',
    img: '/assets/shop/Ingredients/Turmeric_Powder.jpg',
    alt: 'Turmeric Powder',
    details: 'Bright, earthy turmeric for curries, marinades and golden lattes. Store away from direct sunlight.',
  },
  {
    id: 'cinnamon-sticks',
    title: 'Cinnamon Sticks',
    price: 'Rp 45.000',
    stock: 60,
    category: 'spices',
    meta: '50 g • Sweet, aromatic',
    img: '/assets/shop/Ingredients/Cinnamon_Sticks.png',
    alt: 'Cinnamon Sticks',
    details: 'Whole cinnamon sticks for infusions, stews and baking. Tie into sachets or break as needed.',
  },
  {
    id: 'nutmeg-whole',
    title: 'Nutmeg — Whole',
    price: 'Rp 39.000',
    stock: 48,
    category: 'spices',
    meta: '40 g • Warm, sweet spice',
    img: '/assets/shop/Ingredients/Nutmeg_Whole.jpg',
    alt: 'Whole Nutmeg',
    details: 'Whole nutmeg with warm, sweet notes — grate fresh over custards, sauces, and savory dishes.',
  },
  {
    id: 'bay-leaves',
    title: 'Bay Leaves',
    price: 'Rp 18.000',
    stock: 130,
    category: 'spices',
    meta: '15 g • Fragrant, savory',
    img: '/assets/shop/Ingredients/Bay_Leaves.jpg',
    alt: 'Bay Leaves',
    details: 'Fragrant bay leaves for slow-cooked dishes and stocks. Remove before serving.',
  },
  {
    id: 'dried-basil',
    title: 'Dried Basil',
    price: 'Rp 21.000',
    stock: 105,
    category: 'spices',
    meta: '25 g • Sweet herb',
    img: '/assets/shop/Ingredients/Dried_Basil.jpg',
    alt: 'Dried Basil',
    details:
      'Sweet dried basil for pasta sauces, pizzas and Mediterranean dishes. Add toward the end of cooking for best flavor.',
  },
  {
    id: 'thyme-dried',
    title: 'Dried Thyme',
    price: 'Rp 19.000',
    stock: 110,
    category: 'spices',
    meta: '20 g • Robust Mediterranean herb',
    img: '/assets/shop/Ingredients/Dried_Thyme.jpg',
    alt: 'Dried Thyme',
    details: 'Robust thyme for roasting, soups and stews. Holds up well under long cooking.',
  },
  {
    id: 'rosemary-dried',
    title: 'Dried Rosemary',
    price: 'Rp 24.000',
    stock: 92,
    category: 'spices',
    meta: '20 g • Pine-like fragrance',
    img: '/assets/shop/Ingredients/Dried_Rosemary.png',
    alt: 'Dried Rosemary',
    details: 'Piney, aromatic rosemary for roasted meats, potatoes and focaccia. Crush before using to release flavor.',
  },
  {
    id: 'cardamom-pods',
    title: 'Cardamom Pods',
    price: 'Rp 58.000',
    stock: 40,
    category: 'spices',
    meta: '30 g • Floral, citrusy',
    img: '/assets/shop/Ingredients/Cardamom_Pods.jpg',
    alt: 'Cardamom Pods',
    details: 'Floral, citrusy cardamom pods — great in chai, rice dishes and baked goods. Lightly crush to release seeds.',
  },
  {
    id: 'cloves-whole',
    title: 'Cloves — Whole',
    price: 'Rp 36.000',
    stock: 54,
    category: 'spices',
    meta: '25 g • Warm, pungent',
    img: '/assets/shop/Ingredients/Cloves_Whole.png',
    alt: 'Cloves',
    details: 'Warm, pungent whole cloves for spiced drinks, pickles and marinades. Use sparingly, very aromatic.',
  },
  {
    id: 'vanilla-extract',
    title: 'Vanilla Extract',
    price: 'Rp 95.000',
    stock: 28,
    category: 'pantry',
    meta: '50 ml • Pure vanilla',
    img: '/assets/shop/Ingredients/Vanilla_Extract.png',
    alt: 'Vanilla Extract',
    details: 'Pure vanilla extract for baking and desserts. Store sealed away from heat and light for best quality.',
  },
  {
    id: 'saffron-threads',
    title: 'Saffron Threads',
    price: 'Rp 420.000',
    stock: 6,
    category: 'spices',
    meta: '0.5 g • Premium spice',
    img: '/assets/shop/Ingredients/Saffron_Threads.png',
    alt: 'Saffron Threads',
    details:
      'Premium saffron threads — highly aromatic and coloring. Use a few threads infused in warm water for best effect.',
  },
  {
    id: 'matcha-powder',
    title: 'Matcha Powder',
    price: 'Rp 125.000',
    stock: 22,
    category: 'pantry',
    meta: '30 g • Ceremonial grade',
    img: '/assets/shop/Ingredients/Matcha_Powders.jpg',
    alt: 'Matcha Powder',
    details: 'Ceremonial-grade matcha powder for tea, lattes and baking. Sift before whisking to avoid clumps.',
  },
  {
    id: 'baking-powder',
    title: 'Baking Powder',
    price: 'Rp 16.000',
    stock: 180,
    category: 'pantry',
    meta: '200 g • Leavening agent',
    img: '/assets/shop/Ingredients/Baking_Powder.jpg',
    alt: 'Baking Powder',
    details: 'Leavening agent for quick breads and cakes. Keep dry and replace if it loses its rise.',
  },
  {
    id: 'cornstarch',
    title: 'Cornstarch',
    price: 'Rp 14.000',
    stock: 210,
    category: 'pantry',
    meta: '200 g • Thickening agent',
    img: '/assets/shop/Ingredients/Cornstarch.jpg',
    alt: 'Cornstarch',
    details: 'Neutral thickening agent for sauces, gravies and custards. Mix with cold liquid before adding to hot liquids.',
  },
];