export const filters = [
  { value: 'all', label: 'All Categories' },
  { value: 'blenders', label: 'Blenders & Mixers' },
  { value: 'cutlery', label: 'Cutlery & Boards' },
  { value: 'electric', label: 'Electric Kitchen Tools' },
  { value: 'cookware', label: 'Cookware' },
  { value: 'bakeware', label: 'Bakeware' },
  { value: 'storage', label: 'Storage & Containers' },
  { value: 'dinnerware', label: 'Dinnerware & Serveware' },
  { value: 'cleaning', label: 'Cleaning Supplies' },
];

export const products = [
  {
    id: 'hand-blender',
    title: 'Hand Blender',
    price: 'Rp 450.000',
    stock: 75,
    category: 'blenders',
    meta: '600 W • 2-speed • Detachable shaft',
    img: '/assets/shop/Kitchen Tools/600 W Hand_Blender.jpg',
    alt: 'Hand Blender',
    details: 'Compact 600 W immersion blender for soups, sauces, and smoothies. Detachable stainless shaft for easy cleaning. Use the low speed for delicate emulsions and high speed for purees.',
  },
  {
    id: 'stand-mixer',
    title: 'Stand Mixer',
    price: 'Rp 3.200.000',
    stock: 18,
    category: 'blenders',
    meta: '5 L bowl • 6 speeds • Dough hook',
    img: '/assets/shop/Kitchen Tools/Stand_Mixer.jpeg',
    alt: 'Stand Mixer',
    details: 'Powerful stand mixer with 5 L bowl, 6 speeds, whisk, beater, and dough hook. Ideal for baking, whipping cream, and kneading bread dough. Clean attachments with warm soapy water.',
  },
  {
    id: 'personal-blender',
    title: 'Personal Blender',
    price: 'Rp 900.000',
    stock: 42,
    category: 'blenders',
    meta: '600 ml cup • Pulse function',
    img: '/assets/shop/Kitchen Tools/Personal Blender.jpg',
    alt: 'Personal Blender',
    details: 'Single-serve blender with 600 ml travel cup. Perfect for quick smoothies and protein shakes. Twist-to-blend safety design; not for hot liquids.',
  },
  {
    id: 'food-processor',
    title: 'Food Processor',
    price: 'Rp 2.000.000',
    stock: 25,
    category: 'blenders',
    meta: '2 L bowl • 5 blades • 3 speeds',
    img: '/assets/shop/Kitchen Tools/Food Processor.jpg',
    alt: 'Food Processor',
    details: 'Versatile 2 L processor with slicing, shredding, chopping, and dough blades. Prep vegetables, nuts, and pastry in seconds. Pulse for control; never overload the bowl.',
  },
  {
    id: 'juicer',
    title: 'Juicer',
    price: 'Rp 1.400.000',
    stock: 28,
    category: 'blenders',
    meta: 'Slow masticating • Quiet operation',
    img: '/assets/shop/Kitchen Tools/Juicer.jpg',
    alt: 'Juicer',
    details: 'Slow masticating juicer extracts more juice with less foam and noise. Ideal for fruits, leafy greens, and wheatgrass. Rinse parts immediately after use for easier cleaning.',
  },
  {
    id: 'smoothie-maker',
    title: 'Smoothie Maker',
    price: 'Rp 1.100.000',
    stock: 36,
    category: 'blenders',
    meta: '700 W • Ice crush • Travel cup',
    img: '/assets/shop/Kitchen Tools/Smoothie Maker.jpg',
    alt: 'Smoothie Maker',
    details: '700 W smoothie maker with ice-crush blades and on-the-go cup. Blend frozen fruits easily; avoid blending dry ingredients alone.',
  },
  {
    id: 'coffee-grinder',
    title: 'Coffee Grinder',
    price: 'Rp 600.000',
    stock: 58,
    category: 'blenders',
    meta: 'Stainless burrs • 18 grind settings',
    img: '/assets/shop/Kitchen Tools/Coffee Grinder.jpg',
    alt: 'Coffee Grinder',
    details: 'Burr grinder with 18 settings for espresso to French press. Consistent grind size for better flavor. Clean burrs with the included brush; do not wash the motor base.',
  },
  {
    id: 'chopper',
    title: 'Food Chopper',
    price: 'Rp 320.000',
    stock: 90,
    category: 'blenders',
    meta: '500 ml • One-touch chop • Compact',
    img: '/assets/shop/Kitchen Tools/Food Chopper.jpeg',
    alt: 'Food Chopper',
    details: 'One-touch mini chopper for onions, herbs, nuts, and dips. 500 ml bowl with safety lock. Pulse for coarse, hold for fine results.',
  },
  {
    id: 'dough-kneader',
    title: 'Dough Kneader',
    price: 'Rp 1.800.000',
    stock: 22,
    category: 'blenders',
    meta: '1 kg capacity • Auto knead',
    img: '/assets/shop/Kitchen Tools/Dough Kneeder.jpg',
    alt: 'Dough Kneader',
    details: 'Automatic kneader handles up to 1 kg flour. Even, hands-free kneading for bread, pizza, and noodles. Lightly oil the bowl to reduce sticking.',
  },
  {
    id: 'knife-set',
    title: 'Knife Set',
    price: 'Rp 1.200.000',
    stock: 30,
    category: 'cutlery',
    meta: '6 pcs • Stainless steel • Ergonomic handles',
    img: '/assets/shop/Kitchen Tools/Knife Set.jpg',
    alt: 'Knife Set',
    details: "Comprehensive 6‑piece set for everyday prep: chef's, bread, carving, utility, paring, and honing steel. Balanced handles and sharp stainless blades. Hand wash and dry promptly.",
  },
  {
    id: 'chefs-knife',
    title: 'Chef’s Knife',
    price: 'Rp 450.000',
    stock: 65,
    category: 'cutlery',
    meta: '20 cm blade • Full tang',
    img: "/assets/shop/Kitchen Tools/Chef's Knife.jpg",
    alt: "Chef's Knife",
    details: "20 cm full‑tang chef's knife for slicing, dicing, and chopping. Maintain with regular honing; sharpen as needed. Avoid dishwasher.",
  },
  {
    id: 'paring-knife',
    title: 'Paring Knife',
    price: 'Rp 120.000',
    stock: 120,
    category: 'cutlery',
    meta: '9 cm blade • Precision peeling',
    img: '/assets/shop/Kitchen Tools/Paring Knife.jpg',
    alt: 'Paring Knife',
    details: 'Precision 9 cm paring knife ideal for peeling and trimming. Hand wash, dry immediately; store with a blade guard.',
  },
  {
    id: 'bread-knife',
    title: 'Bread Knife',
    price: 'Rp 280.000',
    stock: 70,
    category: 'cutlery',
    meta: 'Serrated • 22 cm blade',
    img: '/assets/shop/Kitchen Tools/Bread Knife.jpg',
    alt: 'Bread Knife',
    details: 'Serrated 22 cm blade glides through crusts without crushing. Avoid glass cutting surfaces to preserve serrations.',
  },
  {
    id: 'carving-knife',
    title: 'Carving Knife',
    price: 'Rp 350.000',
    stock: 55,
    category: 'cutlery',
    meta: 'Long blade • Precision slicing',
    img: '/assets/shop/Kitchen Tools/Carving Knife.jpg',
    alt: 'Carving Knife',
    details: 'Long, thin blade for precise slices of roasts and poultry. Hone before use; hand wash only.',
  },
  {
    id: 'steak-knives',
    title: 'Steak Knives (Set of 6)',
    price: 'Rp 400.000',
    stock: 40,
    category: 'cutlery',
    meta: 'Micro-serrated • Balanced handle',
    img: '/assets/shop/Kitchen Tools/Steak Knifes Set Of 6.jpg',
    alt: 'Steak Knives Set',
    details: 'Micro‑serrated edges stay sharp for table use. Dry thoroughly after washing to prevent water spots.',
  },
  {
    id: 'knife-block',
    title: 'Knife Block',
    price: 'Rp 300.000',
    stock: 48,
    category: 'cutlery',
    meta: 'Universal slots • Non-slip base',
    img: '/assets/shop/Kitchen Tools/Knife Block.jpg',
    alt: 'Knife Block',
    details: 'Universal slot design fits most blades; non‑slip base for stability. Clean slots periodically to remove crumbs.',
  },
  {
    id: 'sharpener',
    title: 'Knife Sharpener',
    price: 'Rp 220.000',
    stock: 85,
    category: 'cutlery',
    meta: '2-stage • Coarse & fine wheels',
    img: '/assets/shop/Kitchen Tools/Knife Sharpener.jpg',
    alt: 'Knife Sharpener',
    details: 'Two‑stage sharpening: coarse restore, fine hone. Draw blade from heel to tip with light pressure.',
  },
  {
    id: 'kitchen-scissors',
    title: 'Kitchen Scissors',
    price: 'Rp 95.000',
    stock: 140,
    category: 'cutlery',
    meta: 'Detachable blades • Bottle opener notch',
    img: '/assets/shop/Kitchen Tools/Kitchen Scissors.jpg',
    alt: 'Kitchen Scissors',
    details: 'Detachable blades for thorough cleaning; integrated opener notch. Dry and oil pivot occasionally.',
  },
  {
    id: 'wooden-cutting-board',
    title: 'Wooden Cutting Board',
    price: 'Rp 220.000',
    stock: 80,
    category: 'cutlery',
    meta: 'Acacia wood • Juice groove • 35×25 cm',
    img: '/assets/shop/Kitchen Tools/Wooden Cutting Board.jpg',
    alt: 'Wooden Cutting Board',
    details: 'Acacia board with juice groove; condition with mineral oil to prevent drying and warping.',
  },
  {
    id: 'plastic-cutting-board',
    title: 'Plastic Cutting Board',
    price: 'Rp 80.000',
    stock: 150,
    category: 'cutlery',
    meta: 'Non-slip feet • Dishwasher-safe • 32×22 cm',
    img: '/assets/shop/Kitchen Tools/Plastic Cutting Board.jpg',
    alt: 'Plastic Cutting Board',
    details: 'Dishwasher‑safe with non‑slip feet; ideal for raw proteins. Replace when deeply scored.',
  },
  {
    id: 'bamboo-cutting-board',
    title: 'Bamboo Cutting Board',
    price: 'Rp 180.000',
    stock: 95,
    category: 'cutlery',
    meta: 'Lightweight • Knife-friendly • 34×24 cm',
    img: '/assets/shop/Kitchen Tools/Bamboo Cutting Board.jpg',
    alt: 'Bamboo Cutting Board',
    details: 'Lightweight, knife‑friendly surface. Hand wash only; oil periodically to maintain finish.',
  },
  {
    id: 'butcher-block',
    title: 'Butcher Block',
    price: 'Rp 1.100.000',
    stock: 15,
    category: 'cutlery',
    meta: 'End-grain • Heavy-duty • 40×30×4 cm',
    img: '/assets/shop/Kitchen Tools/Butcher Block.jpg',
    alt: 'Butcher Block Board',
    details: 'End‑grain board for heavy duty chopping; sanitize with vinegar; re‑oil/wax monthly.',
  },
  {
    id: 'flexible-cutting-mats',
    title: 'Flexible Cutting Mats (Set of 3)',
    price: 'Rp 90.000',
    stock: 130,
    category: 'cutlery',
    meta: 'Color-coded • Anti-slip • 30×22 cm',
    img: '/assets/shop/Kitchen Tools/Flexible Cutting Mats Set Of 3.jpg',
    alt: 'Flexible Cutting Mats Set',
    details: 'Color‑coded mats bend to funnel ingredients; top‑rack dishwasher‑safe.',
  },
  {
    id: 'electric-kettle',
    title: 'Electric Kettle',
    price: 'Rp 350.000',
    stock: 95,
    category: 'electric',
    meta: '1.7 L • Auto shut-off • 2200 W',
    img: '/assets/shop/Kitchen Tools/Electric Kettle.jpg',
    alt: 'Electric Kettle',
    details: '1.7 L, auto shut‑off and boil‑dry protection; descale monthly with diluted vinegar.',
  },
  {
    id: 'toaster',
    title: 'Toaster',
    price: 'Rp 450.000',
    stock: 60,
    category: 'electric',
    meta: '2-slice • 6 browning levels • Defrost',
    img: '/assets/shop/Kitchen Tools/Toaster.jpg',
    alt: 'Toaster',
    details: '2‑slice with defrost and reheat; empty crumb tray regularly; unplug before cleaning.',
  },
  {
    id: 'coffee-maker',
    title: 'Coffee Maker',
    price: 'Rp 1.200.000',
    stock: 32,
    category: 'electric',
    meta: '12-cup • Programmable • Keep warm',
    img: '/assets/shop/Kitchen Tools/Coffee Maker.jpg',
    alt: 'Coffee Maker',
    details: '12‑cup programmable brewer; use medium grind; descale every 1–3 months.',
  },
  {
    id: 'air-fryer',
    title: 'Air Fryer',
    price: 'Rp 1.600.000',
    stock: 40,
    category: 'electric',
    meta: '4 L • Digital controls • 1400 W',
    img: '/assets/shop/Kitchen Tools/Air Fryer.jpg',
    alt: 'Air Fryer',
    details: '4 L, 1400 W with digital presets; shake basket mid‑cook; clean non‑stick parts by hand.',
  },
  {
    id: 'sandwich-maker',
    title: 'Sandwich Maker',
    price: 'Rp 380.000',
    stock: 85,
    category: 'electric',
    meta: 'Non-stick plates • Cut & seal triangles',
    img: '/assets/shop/Kitchen Tools/Sandwich Maker.png',
    alt: 'Sandwich Maker',
    details: 'Non‑stick cut‑and‑seal plates; preheat until light changes; wipe plates when cool.',
  },
  {
    id: 'rice-cooker',
    title: 'Rice Cooker',
    price: 'Rp 550.000',
    stock: 70,
    category: 'electric',
    meta: '1.8 L • Multi-menu • Keep warm 24h',
    img: '/assets/shop/Kitchen Tools/Rice Cooker.jpg',
    alt: 'Rice Cooker',
    details: '1.8 L multi‑menu with 24 h keep‑warm; rinse rice; do not submerge base.',
  },
  {
    id: 'induction-cooktop',
    title: 'Induction Cooktop',
    price: 'Rp 1.300.000',
    stock: 45,
    category: 'electric',
    meta: '2000 W • Touch control • Timer',
    img: '/assets/shop/Kitchen Tools/Induction Cooker.jpg',
    alt: 'Induction Cooktop',
    details: '2000 W touch control; requires magnetic cookware; keep surface dry and clean.',
  },
  {
    id: 'food-steamer',
    title: 'Food Steamer',
    price: 'Rp 600.000',
    stock: 52,
    category: 'electric',
    meta: '2-tier • 60‑min timer • BPA-free baskets',
    img: '/assets/shop/Kitchen Tools/Food Steamer.jpg',
    alt: 'Food Steamer',
    details: '2‑tier BPA‑free baskets; fill reservoir to max line; descale periodically.',
  },
  {
    id: 'electric-grill',
    title: 'Electric Grill',
    price: 'Rp 1.100.000',
    stock: 34,
    category: 'electric',
    meta: 'Non-stick plate • Adjustable temp • 1800 W',
    img: '/assets/shop/Kitchen Tools/Electric Grill.jpg',
    alt: 'Electric Grill',
    details: 'Non‑stick plate, adjustable temp; preheat 5 minutes; drain tray collects grease.',
  },
  {
    id: 'frying-pan-28cm',
    title: 'Frying Pan',
    price: 'Rp 320.000',
    stock: 85,
    category: 'cookware',
    meta: 'Non-stick • Induction-ready • PFOA-free',
    img: '/assets/shop/Kitchen Tools/Frying Pan.jpg',
    alt: 'Frying Pan',
    details: 'PFOA‑free non‑stick, induction‑ready; use silicone/wood utensils; hand wash recommended.',
  },
  {
    id: 'saucepan-1-5l',
    title: 'Saucepan — 1.5 L',
    price: 'Rp 280.000',
    stock: 100,
    category: 'cookware',
    meta: 'Stainless steel • Vented glass lid',
    img: '/assets/shop/Kitchen Tools/Saucepan 15 L.jpg',
    alt: 'Saucepan 1.5 L with lid',
    details: 'Stainless steel with vented lid; medium heat for best results; dishwasher‑safe.',
  },
  {
    id: 'wok-32cm',
    title: 'Wok — 32 cm',
    price: 'Rp 420.000',
    stock: 60,
    category: 'cookware',
    meta: 'Carbon steel • Wooden handle • Flat base',
    img: '/assets/shop/Kitchen Tools/Wok 32 Cm.png',
    alt: 'Wok 32 cm carbon steel',
    details: 'Carbon steel wok; season before first use; high heat stir‑fry; dry immediately to prevent rust.',
  },
  {
    id: 'casserole-3l',
    title: 'Casserole — 3 L',
    price: 'Rp 550.000',
    stock: 44,
    category: 'cookware',
    meta: 'Enameled • Oven-safe • Even heating',
    img: '/assets/shop/Kitchen Tools/Casserole 3L.jpg',
    alt: 'Casserole 3 L with lid',
    details: 'Enameled pot oven‑safe; avoid metal utensils; cool before washing.',
  },
  {
    id: 'stock-pot-8l',
    title: 'Stock Pot — 8 L',
    price: 'Rp 650.000',
    stock: 38,
    category: 'cookware',
    meta: 'Stainless steel • Encapsulated base',
    img: '/assets/shop/Kitchen Tools/Stockpot 8L.jpg',
    alt: 'Stock Pot 8 L stainless steel',
    details: 'Large stainless pot with encapsulated base for even heating; dishwasher‑safe.',
  },
  {
    id: 'pressure-cooker-6l',
    title: 'Pressure Cooker — 6 L',
    price: 'Rp 1.250.000',
    stock: 26,
    category: 'cookware',
    meta: 'Safety lock • Induction base • 2 pressure levels',
    img: '/assets/shop/Kitchen Tools/Pressure Cooker 6L.jpg',
    alt: 'Pressure Cooker 6 L safety lock',
    details: 'Safety lock and dual pressure levels; always check gasket; never overfill past max line.',
  },
  {
    id: 'non-stick-set-5pcs',
    title: 'Non-stick Set — 5 pcs',
    price: 'Rp 1.500.000',
    stock: 34,
    category: 'cookware',
    meta: 'Pans + lids • PFOA-free coating',
    img: '/assets/shop/Kitchen Tools/Non Stick Set 5 PCS.jpg',
    alt: 'Non-stick Cookware Set 5 pcs',
    details: 'Daily cookware bundle; low‑to‑medium heat; avoid aerosol sprays to prolong coating.',
  },
  {
    id: 'griddle',
    title: 'Griddle',
    price: 'Rp 420.000',
    stock: 62,
    category: 'cookware',
    meta: 'Ribbed surface • Even heat • 28×28 cm',
    img: '/assets/shop/Kitchen Tools/Griddle.jpg',
    alt: 'Griddle pan cast aluminum',
    details: 'Ribbed surface for grill marks; preheat; light oiling improves sear and release.',
  },
  {
    id: 'dutch-oven-5l',
    title: 'Dutch Oven — 5 L',
    price: 'Rp 1.800.000',
    stock: 20,
    category: 'cookware',
    meta: 'Enameled cast iron • Oven-safe • Heavy lid',
    img: '/assets/shop/Kitchen Tools/Dutch Oven 1.5L.jpg',
    alt: 'Dutch Oven 5 L cast iron',
    details: 'Enameled cast iron for braises and bakes; avoid thermal shock; hand wash recommended.',
  },
  {
    id: 'baking-trays',
    title: 'Baking Trays (Set of 2)',
    price: 'Rp 180.000',
    stock: 90,
    category: 'bakeware',
    meta: 'Non-stick • 33×23 cm & 39×27 cm',
    img: '/assets/shop/Kitchen Tools/Baking Trails Set Of 2.jpg',
    alt: 'Baking Trays set of 2 non-stick',
    details: 'Non‑stick sheets in two sizes; line with parchment for easy cleanup; oven‑safe to 230°C.',
  },
  {
    id: 'cake-pan-9in',
    title: 'Cake Pan — 9 inch',
    price: 'Rp 120.000',
    stock: 110,
    category: 'bakeware',
    meta: 'Heavy-gauge steel • Even bake',
    img: '/assets/shop/Kitchen Tools/Cake Pan 9 Inch.jpg',
    alt: 'Cake Pan 9 inch round',
    details: 'Heavy‑gauge round pan for even bakes; grease and flour or line with parchment.',
  },
  {
    id: 'muffin-tin-12cup',
    title: 'Muffin Tin — 12 Cup',
    price: 'Rp 160.000',
    stock: 95,
    category: 'bakeware',
    meta: 'Non-stick • Easy release • Standard size',
    img: '/assets/shop/Kitchen Tools/Muffin Tin 12 Cup.png',
    alt: 'Muffin Tin 12 cup non-stick',
    details: 'Standard size non‑stick; use liners or grease lightly; do not use metal tools.',
  },
  {
    id: 'bread-loaf-pan',
    title: 'Bread Loaf Pan',
    price: 'Rp 110.000',
    stock: 120,
    category: 'bakeware',
    meta: 'Non-stick • 22×12×6 cm • Rounded corners',
    img: '/assets/shop/Kitchen Tools/Bread Loaf Pan.jpg',
    alt: 'Bread Loaf Pan 22×12 cm non-stick',
    details: '22×12×6 cm loaf pan; non‑stick corners; cool 10 minutes before turning out.',
  },
  {
    id: 'pizza-pan-32cm',
    title: 'Pizza Pan — 32 cm',
    price: 'Rp 130.000',
    stock: 88,
    category: 'bakeware',
    meta: 'Perforated • Crisp crust • Non-stick',
    img: '/assets/shop/Kitchen Tools/Pizza Pan 32 CM.jpg',
    alt: 'Pizza Pan 32 cm perforated',
    details: 'Perforated for crisp crusts; dust lightly with cornmeal; oven‑safe to 230°C.',
  },
  {
    id: 'cooling-rack',
    title: 'Cooling Rack',
    price: 'Rp 90.000',
    stock: 140,
    category: 'bakeware',
    meta: 'Stainless steel • 40×25 cm • Oven-safe',
    img: '/assets/shop/Kitchen Tools/Cooling Rack.jpg',
    alt: 'Cooling Rack 40×25 cm stainless steel',
    details: 'Stainless rack 40×25 cm; elevates bakes for airflow; doubles as roasting rack.',
  },
  {
    id: 'rolling-pin',
    title: 'Rolling Pin',
    price: 'Rp 75.000',
    stock: 160,
    category: 'bakeware',
    meta: 'Beechwood • 40 cm • Smooth roll',
    img: '/assets/shop/Kitchen Tools/Rolling Pin.jpg',
    alt: 'Rolling Pin beechwood 40 cm',
    details: 'Beechwood 40 cm; flour lightly; wipe clean and avoid soaking to prevent warping.',
  },
  {
    id: 'mixing-bowls-3pcs',
    title: 'Mixing Bowls (Set of 3)',
    price: 'Rp 220.000',
    stock: 76,
    category: 'bakeware',
    meta: 'Stainless steel • Tight lids • Nesting design',
    img: '/assets/shop/Kitchen Tools/Mixing Bowls Set Of 3.jpg',
    alt: 'Mixing Bowls set of 3 stainless steel with lids',
    details: 'Nesting stainless bowls with lids; non‑reactive; fridge and dishwasher‑safe.',
  },
  {
    id: 'pastry-brush',
    title: 'Pastry Brush',
    price: 'Rp 45.000',
    stock: 190,
    category: 'bakeware',
    meta: 'Silicone • Heat-resistant • Easy clean',
    img: '/assets/shop/Kitchen Tools/Pastry Brush.jpg',
    alt: 'Pastry Brush silicone heat resistant',
    details: 'Silicone bristles resist heat and odors; safe for dishwasher top rack.',
  },
  {
    id: 'food-storage-boxes-10pcs',
    title: 'Food Storage Boxes (10 pcs)',
    price: 'Rp 260.000',
    stock: 70,
    category: 'storage',
    meta: 'BPA-free • Microwave-safe • Airtight lids',
    img: '/assets/shop/Kitchen Tools/Food Storages.jpg',
    alt: 'Food Storage Boxes set of 10 with lids BPA-free',
    details: 'BPA‑free, microwave and freezer‑safe; vent lid when microwaving; avoid staining foods hot.',
  },
  {
    id: 'glass-jars-6pcs',
    title: 'Glass Jars (Set of 6)',
    price: 'Rp 180.000',
    stock: 100,
    category: 'storage',
    meta: '500 ml • Airtight clamp lids • Clear glass',
    img: '/assets/shop/Kitchen Tools/Glass Jars Set Of 6.png',
    alt: 'Glass Jars set of 6 airtight lids 500 ml each',
    details: '500 ml clamp‑lid jars; airtight for dry goods; hand wash seals for longevity.',
  },
  {
    id: 'spice-containers-12pcs',
    title: 'Spice Containers (12 pcs)',
    price: 'Rp 140.000',
    stock: 120,
    category: 'storage',
    meta: 'Shaker lids • Labels included • Rack-ready',
    img: '/assets/shop/Kitchen Tools/Spice Containers 12pcs.jpg',
    alt: 'Spice Containers set of 12 labels shaker lids rack-ready',
    details: 'Shaker lids with labels; fill with a funnel; keep away from heat and light.',
  },
  {
    id: 'lunch-box-stainless',
    title: 'Lunch Box — Stainless Steel',
    price: 'Rp 150.000',
    stock: 85,
    category: 'storage',
    meta: 'Leak-proof • 1 L • Removable divider',
    img: '/assets/shop/Kitchen Tools/LunchBox - Stainless Steel.jpg',
    alt: 'Lunch Box stainless steel leak-proof 1 L',
    details: 'Leak‑proof 1 L with divider; not microwave‑safe; hand wash lid gasket.',
  },
  {
    id: 'airtight-containers-set',
    title: 'Airtight Containers (Set)',
    price: 'Rp 240.000',
    stock: 76,
    category: 'storage',
    meta: 'Stackable • BPA-free • Assorted sizes',
    img: '/assets/shop/Kitchen Tools/Air Tight Containers.png',
    alt: 'Airtight Containers set stackable BPA-free assorted sizes',
    details: 'Stackable BPA‑free canisters for pantry staples; wash before first use; dry thoroughly.',
  },
  {
    id: 'fridge-storage-bins',
    title: 'Fridge Storage Bins (Set of 4)',
    price: 'Rp 220.000',
    stock: 64,
    category: 'storage',
    meta: 'Clear • Pull-out handles • BPA-free',
    img: '/assets/shop/Kitchen Tools/Fridge Storage BIns Set Of 4.jpg',
    alt: 'Fridge Storage Bins set of 4 clear pull-out handles',
    details: 'Clear bins with handles for easy access; not dishwasher‑safe; wipe with mild soap.',
  },
  {
    id: 'oil-dispenser-500ml',
    title: 'Oil Dispenser — 500 ml',
    price: 'Rp 85.000',
    stock: 120,
    category: 'storage',
    meta: 'Drip-free spout • Measurement window • Glass',
    img: '/assets/shop/Kitchen Tools/Oil Dispenser.png',
    alt: 'Oil Dispenser 500 ml drip-free spout glass bottle',
    details: 'Glass bottle with drip‑free spout and measure window; clean spout regularly to prevent clogs.',
  },
  {
    id: 'plastic-containers-set',
    title: 'Plastic Containers (Set)',
    price: 'Rp 120.000',
    stock: 140,
    category: 'storage',
    meta: 'Microwave-safe • Nesting • Secure lids',
    img: '/assets/shop/Kitchen Tools/Plastic Containers.jpg',
    alt: 'Plastic Containers set nesting microwave-safe assorted',
    details: 'Nesting set with secure lids; microwave with lid vented; avoid harsh scrubbers.',
  },
  {
    id: 'pantry-organizer-shelf',
    title: 'Pantry Organizer Shelf',
    price: 'Rp 140.000',
    stock: 88,
    category: 'storage',
    meta: 'Expandable • Multi-tier • Sturdy steel',
    img: '/assets/shop/Kitchen Tools/Pantry Organizer Shelf.jpg',
    alt: 'Pantry Organizer shelf expandable multi-tier',
    details: 'Expandable multi‑tier rack increases vertical space; wipe clean with damp cloth.',
  },
  {
    id: 'plates-4pcs',
    title: 'Plates (Set of 4)',
    price: 'Rp 280.000',
    stock: 72,
    category: 'dinnerware',
    meta: 'Porcelain • 26 cm • Chip-resistant',
    img: '/assets/shop/Kitchen Tools/Plates Set Of 4.jpg',
    alt: 'Plates set of 4 porcelain 26 cm white',
    details: '26 cm porcelain dinner plates; microwave and dishwasher‑safe; chip‑resistant glaze.',
  },
  {
    id: 'bowls-4pcs',
    title: 'Bowls (Set of 4)',
    price: 'Rp 220.000',
    stock: 84,
    category: 'dinnerware',
    meta: 'Porcelain • 15 cm • Microwave-safe',
    img: '/assets/shop/Kitchen Tools/Bowl Set Of 4.jpg',
    alt: 'Bowls set of 4 porcelain 15 cm soup bowls white',
    details: '15 cm soup/cereal bowls; microwave‑safe porcelain; stackable design.',
  },
  {
    id: 'cups-mugs-4pcs',
    title: 'Cups & Mugs (Set of 4)',
    price: 'Rp 200.000',
    stock: 96,
    category: 'dinnerware',
    meta: 'Ceramic • 300 ml • Comfortable handle',
    img: '/assets/shop/Kitchen Tools/CupsMugsSet4.png',
    alt: 'Cups and Mugs set of 4 ceramic 300 ml assorted colors',
    details: '300 ml ceramic mugs with comfy handles; microwave and dishwasher‑safe.',
  },
  {
    id: 'serving-tray',
    title: 'Serving Tray',
    price: 'Rp 160.000',
    stock: 78,
    category: 'dinnerware',
    meta: 'Wood • Integrated handles • 45×30 cm',
    img: '/assets/shop/Kitchen Tools/Serving Trays.jpg',
    alt: 'Serving Tray wood rectangular handles 45×30 cm',
    details: 'Wood tray with integrated handles; wipe clean; oil occasionally to protect finish.',
  },
  {
    id: 'cutlery-set-16pcs',
    title: 'Cutlery Set — 16 pcs',
    price: 'Rp 380.000',
    stock: 66,
    category: 'dinnerware',
    meta: 'Stainless steel • Service for 4 • Mirror finish',
    img: '/assets/shop/Kitchen Tools/Cutlery Set of 16 pcs.jpg',
    alt: 'Cutlery Set 16 pcs stainless steel mirror finish service for 4',
    details: 'Service for four with mirror finish; dry promptly to reduce spotting; dishwasher‑safe top rack.',
  },
  {
    id: 'glassware-6pcs',
    title: 'Glassware (Set of 6)',
    price: 'Rp 300.000',
    stock: 72,
    category: 'dinnerware',
    meta: 'Tumblers • 360 ml • Crystal-clear glass',
    img: '/assets/shop/Kitchen Tools/Glassware Set of 6.jpg',
    alt: 'Glassware set of 6 tumblers 360 ml crystal clear',
    details: '360 ml tumblers in crystal‑clear glass; avoid sudden temperature changes; dishwasher‑safe.',
  },
  {
    id: 'pitcher-1-5l',
    title: 'Pitcher — 1.5 L',
    price: 'Rp 150.000',
    stock: 88,
    category: 'dinnerware',
    meta: 'Glass • Tight lid • Easy-pour spout',
    img: '/assets/shop/Kitchen Tools/Pitcher 1.5l.jpg',
    alt: 'Pitcher 1.5 L glass lid spout for iced tea or juice',
    details: 'Glass pitcher with tight lid and pour spout; ideal for iced tea/juice; hand wash lid.',
  },
  {
    id: 'serving-bowl-large',
    title: 'Serving Bowl — Large',
    price: 'Rp 180.000',
    stock: 76,
    category: 'dinnerware',
    meta: 'Porcelain • 28 cm • Wide rim',
    img: '/assets/shop/Kitchen Tools/Serving Bowl Large.jpg',
    alt: 'Serving Bowl large 28 cm porcelain white',
    details: '28 cm porcelain bowl with wide rim; microwave and dishwasher‑safe.',
  },
  {
    id: 'napkin-holder',
    title: 'Napkin Holder',
    price: 'Rp 70.000',
    stock: 130,
    category: 'dinnerware',
    meta: 'Weighted arm • Stainless steel • Modern design',
    img: '/assets/shop/Kitchen Tools/Napkin Holder.jpg',
    alt: 'Napkin Holder stainless steel weighted arm modern design',
    details: 'Weighted‑arm stainless holder keeps napkins in place; wipe clean with a damp cloth.',
  },
  {
    id: 'dish-brush',
    title: 'Dish Brush',
    price: 'Rp 35.000',
    stock: 200,
    category: 'cleaning',
    meta: 'Replaceable head • Ergonomic grip • Stiff bristles',
    img: '/assets/shop/Kitchen Tools/Dish Brush.png',
    alt: 'Dish Brush ergonomic handle replaceable head stiff bristles',
    details: 'Ergonomic handle with replaceable head; stiff bristles cut grease; rinse and air‑dry after use.',
  },
  {
    id: 'sponges-6pack',
    title: 'Sponges (6-pack)',
    price: 'Rp 25.000',
    stock: 240,
    category: 'cleaning',
    meta: 'Dual-sided • Scrubber + foam • Long-lasting',
    img: '/assets/shop/Kitchen Tools/Sponge 6 Set.jpg',
    alt: 'Sponges 6-pack dual side scrubber soft foam kitchen cleaning',
    details: 'Dual‑sided scrub + foam; sanitize by microwaving damp sponge 1 min; replace regularly.',
  },
  {
    id: 'dish-rack',
    title: 'Dish Rack',
    price: 'Rp 280.000',
    stock: 48,
    category: 'cleaning',
    meta: '2-tier • Drip tray • Utensil holder • Rust-resistant',
    img: '/assets/shop/Kitchen Tools/Dish Rack.jpg',
    alt: 'Dish Rack 2-tier stainless steel drip tray utensil holder',
    details: '2‑tier stainless rack with drip tray and utensil holder; empty tray often; wipe to prevent spots.',
  },
  {
    id: 'spray-bottles-2pcs',
    title: 'Spray Bottles (2 pcs)',
    price: 'Rp 40.000',
    stock: 150,
    category: 'cleaning',
    meta: 'Adjustable nozzle • 500 ml • Leak-proof',
    img: '/assets/shop/Kitchen Tools/Spray Bottles 2 Pcs.jpg',
    alt: 'Spray Bottles set of 2 adjustable nozzle 500 ml each for cleaning solutions',
    details: '500 ml adjustable nozzles; ideal for DIY cleaners; do not store strong acids long‑term.',
  },
  {
    id: 'mop',
    title: 'Mop',
    price: 'Rp 120.000',
    stock: 90,
    category: 'cleaning',
    meta: 'Microfiber head • Adjustable handle • Bucket compatible',
    img: '/assets/shop/Kitchen Tools/Mop.jpg',
    alt: 'Mop microfiber head bucket compatible adjustable handle home cleaning tool',
    details: 'Microfiber head with adjustable handle; machine‑wash head; avoid fabric softeners.',
  },
  {
    id: 'cleaning-cloths-6pcs',
    title: 'Cleaning Cloths (6 pcs)',
    price: 'Rp 45.000',
    stock: 200,
    category: 'cleaning',
    meta: 'Microfiber • Lint-free • Super absorbent',
    img: '/assets/shop/Kitchen Tools/Cloth 6 pcs.jpg',
    alt: 'Cleaning Cloths microfiber set of 6 lint-free absorbent reusable towels',
    details: 'Microfiber, lint‑free towels; wash before first use; no bleach; air‑dry or low heat.',
  },
  {
    id: 'bucket-12l',
    title: 'Bucket — 12 L',
    price: 'Rp 55.000',
    stock: 120,
    category: 'cleaning',
    meta: 'Durable plastic • Metal handle • Pour spout',
    img: '/assets/shop/Kitchen Tools/Bucket.png',
    alt: 'Bucket 12 L durable plastic metal handle pour spout for cleaning and mopping',
    details: 'Durable plastic with metal handle and pour spout; rinse after use; store dry.',
  },
  {
    id: 'dustpan-and-brush',
    title: 'Dustpan & Brush',
    price: 'Rp 50.000',
    stock: 140,
    category: 'cleaning',
    meta: 'Soft bristles • Clip-on design • Compact storage',
    img: '/assets/shop/Kitchen Tools/Dushpan & Brush.jpg',
    alt: 'Dustpan and Brush set soft bristles clip-on compact household cleaning tool',
    details: 'Soft bristles with clip‑on pan for compact storage; tap to release dust; rinse as needed.',
  },
  {
    id: 'scrubber',
    title: 'Scrubber',
    price: 'Rp 30.000',
    stock: 180,
    category: 'cleaning',
    meta: 'Non-scratch • Ergonomic handle • Tough on grime',
    img: '/assets/shop/Kitchen Tools/Scrubber.jpg',
    alt: 'Scrubber handheld non-scratch kitchen tile grout cleaning tool ergonomic',
    details: 'Non‑scratch handheld scrubber for kitchen and tile; use with mild cleaners; rinse thoroughly.',
  },
];