export const appetizerRecipes = [
  {
    id: "florentine-ciabatta",
    name: "Florentine Ciabatta",
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalTime: "25 mins",
    difficulty: "Easy",
    rating: 4.5,
    reviews: 350,
    image: "../../assets/appetizers/Florentine Ciabatta.jpg",
    description: "There's something undeniably magical about biting into a perfectly toasted Florentine Ciabatta. Each bite is a melody of textures and flavors, cozy yet bold, comforting yet exciting. It's not just a sandwich it's an experience.",
    ingredients: [
      "1 large loaf Ciabatta Bread",
      "2 cups fresh spinach",
      "1 cup shredded mozarella cheese",
      "4 slices provolone cheese",
      "1/3 cup sun-dried tomatoes",
      "2 cloves minced garlic",
      "1 tablespoon olive oil",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "A pinch crushed red pepper flakes"
    ],
    instructions: [
      { step: "Preheat Your Equipment", details: ["Heat a skillet or grill pan over medium heat.", "If you have a sandwich press, set it to medium."] },
      { step: "Combine Ingredients", details: ["In a skillet, heat olive oil and sauté garlic for 30 seconds.", "Add spinach and cook until just wilted.", "Season with salt and pepper."] },
      { step: "Prepare Your Cooking Vessel", details: ["Lightly brush the outside of the ciabatta slices with olive oil to promote even toasting."] },
      { step: "Assemble the Dish", details: ["Layer mozzarella and provolone on both inner sides of the ciabatta. Top one side with spinach and sun-dried tomatoes. Close the sandwich."] },
      { step: "Finishing Touches and Serving", details: ["Place the sandwich in the skillet and press with a spatula. Cook 3–4 minutes per side until the bread is golden and the cheese is melted.", "Remove from the skillet and let rest for 1–2 minutes before slicing.", "Slice in halves or quarters, serve warm, and savor every bite of melty, crispy, tangy goodness."] }
    ],
    nutrition: {
      calories: 200,
      carbs: "19g",
      protein: "5g",
      fat: "12g",
      saturatedFat: "3g",
      transFat: "0g",
      cholesterol: "8mg",
      sodium: "258mg",
      potassium: "39.1mg",
      fiber: "1g",
      sugar: "1g",
      vitaminD: "0mcg",
      calcium: "45mg",
      iron: "1.1mg"
    },
    tags: ["Appetizer", "Ciabatta", "Bread Crumbs", "Easy", "Family Favorite"]
  },
  {
    id: "party-cheese-bread",
    name: "Party Cheese Bread",
    prepTime: "25 mins",
    cookTime: "30 mins",
    totalTime: "55 mins",
    difficulty: "Easy",
    rating: 5,
    reviews: 210,
    image: "../../assets/appetizers/Party Cheese Bread.jpg",
    description: "This Party Cheese Bread is a show-stopping appetizer that combines warm, gooey cheese with crispy sourdough bread, infused with butter, garlic, and Dijon mustard. It's perfect for gatherings, game nights, or as a delicious alternative to traditional garlic bread.",
    ingredients: [
      "1 round loaf sourdough bread",
      "1 pound Monterey Jack Cheese, sliced",
      "2 tablespoons lemon juice",
      "2 tablespoons Dijon mustard",
      "1-1/2 teaspoons garlic powder",
      "1/2 teaspoon onion powder",
      "1/2 teaspoon celery salt",
      "Minced fresh chives, optional"
    ],
    instructions: [
      { step: "", details: ["Preheat the oven to 350°F.", "Cut the bread into 1-inch slices, making sure not to cut all the way through, leaving about 1/2 inch at the bottom to keep the loaf intact. Repeat in the opposite direction to create a crosshatch pattern.", "Insert the sliced cheese into the cuts between the bread slices.", "In a small bowl, mix the melted butter, lemon juice, Dijon mustard, garlic powder, onion powder, and celery salt. Drizzle this mixture evenly over the bread.", "Wrap the bread in foil and place it on a baking sheet. Bake for 20 minutes.", "Unwrap the foil and bake for an additional 10 minutes, or until the cheese is fully melted and bubbly.", "If desired, sprinkle with fresh chives before serving. Serve warm."] }
    ],
    nutrition: {
      calories: 237,
      carbs: "15g",
      protein: "10g",
      fat: "15g",
      saturatedFat: "9g",
      transFat: "0g",
      cholesterol: "41mg",
      sodium: "468mg",
      potassium: "33.6mg",
      fiber: "0.84g",
      sugar: "0.83g",
      vitaminC: "0mg",
      calcium: "36mg",
      iron: "1mg"
    },
    tags: ["Appetizer", "Cheese", "Bread", "Party"]
  },
  {
    id: "cheese-biscuit-stacks",
    name: "Ham 'n' Cheese Biscuit Stacks",
    prepTime: "10 mins",
    cookTime: "15 mins",
    totalTime: "25 mins",
    difficulty: "Easy",
    rating: 4,
    reviews: 212,
    image: "../../assets/appetizers/Ham 'n' Cheese Biscuit Stacks.jpg",
    description: "Enjoy a quick and tasty breakfast with Easy Ham and Cheese Biscuit Stacks. Perfect for busy mornings, these delicious stacks are ready in minutes!",
    ingredients: [
      "2 cups biscuit mix",
      "1 cup shredded cheddar cheese",
      "1 cup diced ham",
      "1/2 cup milk",
      "1/4 cup melted butter",
      "Salt and pepper to taste",
      "Fresh fruit salad",
      "Crispy bacon",
      "A cup of hot coffee or tea"
    ],
    instructions: [
      { step: "", details: ["Preheat the oven to 400°F (200°C).", "In a large bowl, combine the biscuit mix, shredded cheddar cheese, diced ham, milk, and melted butter.", "Mix until just combined, being careful not to overmix.", "Scoop the mixture onto a greased baking sheet, forming stacks of biscuit dough.", "Bake in the preheated oven for 15-20 minutes or until golden brown.", "Serve warm with fresh fruit salad and crispy bacon on the side.", "Enjoy with a cup of hot coffee or tea."] }
    ],
    nutrition: {
      calories: 631,
      carbs: "55.2g",
      protein: "23.7g",
      fat: "31.5g",
      saturatedFat: "15.8g",
      transFat: "0g",
      cholesterol: "79mg",
      sodium: "1420mg",
      potassium: "237mg",
      fiber: "3.2g",
      sugar: "7.9g",
      vitaminD: "0.8mcg",
      calcium: "315mg",
      iron: "3.2mg"
    },
    tags: ["Appetizer", "Ham & Cheese", "Biscuit", "Easy", "Family Favorite"],
    video: "https://www.youtube.com/embed/rsKVOr0EoIQ?si=6qvjDgWgdMWxfNVL"
  },
  {
    id: "stuffed-cherry-tomatoes",
    name: "Stuffed Cherry Tomatoes",
    prepTime: "20 mins",
    cookTime: "20 mins",
    totalTime: "40 mins",
    difficulty: "Easy",
    rating: 4.5,
    reviews: 320,
    image: "../../assets/appetizers/Stuffed Cherry Tomatoes.jpg",
    description: "Stuffed cherry tomatoes filled with cream cheese, parmesan and herbs. The perfect summer appetizer when cherry tomatoes are in season and excellent bite-size food for outdoor entertaining.",
    ingredients: [
      "1/2 cup cream cheese",
      "4 tablespoons parmesan powder",
      "1 teaspoon dried parsley",
      "1-2 tablespoons fresh dill",
      "1/2 teaspoon garlic powder",
      "Black pepper",
      "Paprika"
    ],
    instructions: [
      { step: "", details: ["Rinse cherry tomatoes under running water and pat them dry. Cut off the top where the stem was. With a sharp-point knife, cut around the center of the tomato (This will make it easier to scoop the middle part out). With a small spoon or a measuring spoon - 1/4 teaspoon works great, remove all the seeds.", "When done, level off the tomato by cutting a very small piece off the bottom. Place it onto a paper kitchen towel, the open side down, to get rid of any excess juices."] },
      { step: "For the Filling", details: ["In a bowl, mix all the ingredients together until well combined. Taste and adjust to your liking, if needed.", "Transfer the filling into one of the corners of a Ziploc bag. With scissors, cut a small hole and fill each cherry tomato up to the top and a little bit over. Sprinkle with paprika."] },
      { step: "Serving", details: ["Serve right away or refrigerate (for best results, put them in an airtight container) until ready to serve."] }
    ],
    nutrition: {
      calories: 24,
      carbs: "1g",
      protein: "1g",
      fat: "2g",
      saturatedFat: "1g",
      transFat: "0.8g",
      cholesterol: "7mg",
      sodium: "35mg",
      fiber: "0.02g",
      sugar: "0.2g",
      iron: "0.02g",
      vitaminC: "1mg",
      vitaminD: "0.25mg"
    },
    tags: ["Appetizer", "Cherry Tomatoes", "Sweet", "Vegetarian", "Easy", "Family Favorite"],
    video: "https://www.youtube.com/embed/9Er_RqoBZ_M?si=4sUERHIsfHTVYgwG"
  },
  {
    id: "fried-prosciutto-tortellini",
    name: "Fried Prosciutto Tortellini",
    prepTime: "25 mins",
    cookTime: "5 mins",
    totalTime: "30 mins",
    difficulty: "Easy",
    rating: 3.5,
    reviews: 220,
    image: "../../assets/appetizers/Fried Prosciutto Tortellini.jpg",
    description: "These Fried Prosciutto Tortellini are a crispy and delicious appetizer that will impress your guests. The tortellini are filled with cheese and prosciutto, then coated in breadcrumbs and fried until golden brown. Serve them with marinara sauce for dipping and watch them disappear!",
    ingredients: [
      "2 large eggs",
      "2 tablespoons 2% milk",
      "2/3 cup seasoned bread crumbs",
      "1 teaspoon garlic powder",
      "2 tablespoons grated Pecorino Romano Cheese",
      "1 tablespoon minced fresh parsley",
      "1/2 teaspoon salt",
      "Oil for frying",
      "1 package refrigerated Prosciutto Ricotta Tortellini",
      "1 tablespoon olive oil",
      "3 tablespoons finely chopped onion",
      "4 garlic cloves, coarsely chopped",
      "1 can (15 ounces) tomato puree",
      "1 tablespoon minced fresh basil",
      "1/4 teaspoon salt",
      "1/4 teaspoon pepper",
      "Additional minced fresh basil"
    ],
    instructions: [
      { step: "", details: ["In a small bowl, whisk together eggs and milk. In another bowl, stir together the next 5 ingredients.", "In a cast-iron or other heavy skillet, heat 1/4 in. oil to 375°. Dip tortellini in egg mixture, then in bread crumb mixture to coat. Fry tortellini in batches, adding oil as necessary, until golden brown, 1-1/2 to 2 minutes on each side. Drain on paper towels.", "Meanwhile, in a small saucepan, heat 1 tablespoon olive oil over medium heat. Add onion and garlic, cooking until softened. Stir in tomato puree, basil, salt and pepper; bring to a boil. Reduce heat (simmer), uncovered, 10 minutes. Sprinkle with minced fresh basil.", "Serve tortellini with tomato sauce for dipping."] }
    ],
    nutrition: {
      calories: 48,
      carbs: "5g",
      protein: "1g",
      fat: "2g",
      saturatedFat: "1g",
      transFat: "0g",
      sodium: "98g",
      fiber: "0g",
      sugars: "0g"
    },
    tags: ["Appetizer", "Tortellini", "Prosciutto", "Italian Street Food", "Easy"],
    video: "https://www.youtube.com/embed/mYBZw7hrWPM?si=3sMEixa9GIrf2dUI"
  },
  {
    id: "artichoke-dip",
    name: "Hot Spinach Artichoke Dip",
    prepTime: "15 mins",
    cookTime: "25 mins",
    totalTime: "40 mins",
    difficulty: "Medium",
    rating: 4.5,
    reviews: 239,
    image: "../../assets/appetizers/Hot Spinach Artichoke Dip.jpg",
    description: "This spinach artichoke dip is delicious. It's so cheesy and fragrant. If you don't like artichokes, don't worry — you'll never know they're in there! My only question is: Is it okay to eat it with a spoon right out of the dish?",
    ingredients: [
      "1 (8 ounce) package cream cheese, softened",
      "1/4 cup mayonnaise",
      "1/4 cup grated Parmesan cheese",
      "1/4 cup grated Romano cheese",
      "1 clove garlic, peeled and minced",
      "1/2 teaspoon dried basil",
      "1/4 teaspoon garlic salt",
      "Salt and pepper to taste",
      "1 (14 ounce) can artichoke hearts, drained and chopped",
      "1/2 cup frozen chopped spinach, thawed and drained",
      "1/4 cup shredded mozzarella cheese"
    ],
    instructions: [
      { step: "", details: ["Gather all ingredients. Preheat the oven to 350 degrees F (175 degrees C). Lightly grease a small baking dish.", "Mix cream cheese, mayonnaise, Parmesan cheese, Romano cheese, garlic, basil, garlic salt, salt, and pepper together in a medium bowl.", "Gently stir in artichoke hearts and spinach.", "Transfer the mixture to the prepared baking dish; top with mozzarella cheese.", "Bake in the preheated oven until bubbly and lightly browned, about 25 minutes."] }
    ],
    nutrition: {
      calories: 134,
      carbs: "3g",
      protein: "4g",
      fat: "12g",
      saturatedFat: "6g",
      transFat: "0g",
      cholesterol: "28mg",
      sodium: "315mg",
      potassium: "54mg",
      fiber: "1g",
      sugar: "0g",
      vitaminC: "3mg",
      calcium: "88mg"
    },
    tags: ["Appetizer", "Artichokes", "Cheese", "Medium", "Family Favorite"],
    video: "https://www.youtube.com/embed/vVGJgihkM6w?si=fjn8MP9nAPUAcrc5"
  },
  {
    id: "grilled-pizza",
    name: "Grilled Tomato-Peach Pizza",
    prepTime: "20 mins",
    cookTime: "5 mins",
    totalTime: "25 mins",
    difficulty: "Easy",
    rating: 4.5,
    reviews: 195,
    image: "../../assets/appetizers/Grilled Tomato-Peach Pizza.jpg",
    description: "Imagine the sun is setting, the grill is hot, and there's a sweet summer breeze floating through the backyard. That's the exact moment this Grilled Tomato-Peach Pizza was made for. With juicy, char-kissed peaches, vine-ripened tomatoes, and creamy mozzarella all resting on a smoky grilled crust, every bite bursts with bright, fresh flavor.",
    ingredients: [
      "4 medium tomatoes, thinly sliced",
      "1/4 teaspoon salt",
      "2 medium peaches, halved",
      "Cooking spray",
      "1 tablespoon cornmeal",
      "1 tube (13-1/2 ounces) refrigerated pizza crust",
      "4 ounces fresh mozzarella cheese, sliced",
      "6 fresh basil leaves, thinly sliced",
      "1/8 teaspoon coarsely ground pepper"
    ],
    instructions: [
      { step: "", details: ["Sprinkle tomatoes with salt (let it stand for 15 minutes). Drain tomatoes on paper towels and pat dry.", "Grill peaches on an oiled grill rack, covered, over medium heat or broil 4 in. from heat until peaches have grill marks and are tender, 2-3 minutes on each side, turning once. Remove peaches; cool slightly. Cut into slices.", "Coat a 15x10x1-in. baking pan with cooking spray; sprinkle with cornmeal. Unroll crust into pan, pressing into a 12x10-in. rectangle. Spritz with cooking spray. Invert crust onto grill. Grill, covered, over medium heat until bottom is lightly browned, 2-3 minutes. Remove from grill, inverting onto baking pan.", "Layer grilled side of pizza with tomatoes, peaches and cheese. Return pizza to grill. Cook, covered, until crust is lightly browned and cheese is melted, 3-4 minutes, rotating halfway through cooking to ensure an evenly browned crust. Sprinkle with basil and pepper."] }
    ],
    nutrition: {
      calories: 98,
      carbs: "15g",
      protein: "4g",
      fat: "3g",
      saturatedFat: "1g",
      transFat: "0g",
      cholesterol: "6mg",
      sodium: "208mg",
      fiber: "1g",
      sugar: "3g",
      calcium: "312.6mg",
      iron: "15.2mg",
      vitaminC: "284.7mg"
    },
    tags: ["Appetizer", "Pizza", "Easy", "French"],
    video: "https://www.youtube.com/embed/J-56bxHry0A?si=pjRW0UzjVJRUjseb"
  },
  {
    id: "meatballs",
    name: "Orange Marmalade Meatballs",
    prepTime: "30 mins",
    cookTime: "0 mins",
    totalTime: "30 mins",
    difficulty: "Easy",
    rating: 5,
    reviews: 201,
    image: "../../assets/appetizers/Orange Marmalade Meatballs.jpg",
    description: "Orange marmalade meatballs are sweet and tangy with just a touch of spice. Made with only five ingredients, these glazed orange meatballs are perfect for an easy weeknight meal or a crowd-pleasing party appetizer.",
    ingredients: [
      "1 package (22 ounces) frozen fully cooked Angus beef meatballs",
      "1 jar (12 ounces) orange marmalade",
      "1/4 cup orange juice",
      "3 green onions, chopped, divided",
      "1 jalapeno pepper, seeded and chopped"
    ],
    instructions: [
      { step: "", details: ["Start by preheating your oven to 400°F (200°C). Line a baking sheet with parchment paper to prevent the meatballs from sticking—this makes cleanup a breeze.", "In a large bowl, mix together the ground meat, breadcrumbs, Parmesan cheese, chopped onion, minced garlic, egg, salt, pepper, oregano, and thyme. Use your hands or a spoon to combine everything until it's well blended.", "Take small portions of the mixture and roll them into balls about 1 inch in diameter. Place each meatball onto your prepared baking sheet. You should get about 20-24 meatballs.", "While the meatballs are baking, let's make the sweet sauce. In a small saucepan, combine the orange marmalade, soy sauce, and rice vinegar. Heat over medium until everything is melted and well mixed.", "If you want your sauce a bit thicker, mix the cornstarch with a little water to create a slurry. Add this to the sauce and cook for a few more minutes until it thickens to your desired consistency. This step is optional, but it gives a nice coating.", "Once the meatballs are baked, take them out of the oven and transfer them to a serving dish. Pour the delicious sauce over the meatballs and gently toss them to coat evenly.", "Finish by garnishing your meatballs with sliced green onions for a pop of color and flavor. Serve them warm and provide toothpicks for easy picking! These are perfect for parties or family gatherings."] }
    ],
    nutrition: {
      calories: 15.62,
      carbs: "3.79g",
      protein: "0.05g",
      fat: "0.09g",
      saturatedFat: "0g",
      transFat: "0g",
      cholesterol: "0.21mg",
      sodium: "27.59mg",
      potassium: "8.28mg",
      fiber: "0.06g",
      sugar: "3.09g",
      vitaminC: "3mg",
      calcium: "3mg"
    },
    tags: ["Main Course", "Arugula", "Salad", "Prosciutto", "Easy", "Everbody's Favorite"],
    video: "https://www.youtube.com/embed/8AcuwACDhWU?si=Iq1RZxelb8mi-EBd"
  }
];
