export const filters = [
  { value: 'all', label: 'All Categories' },
  { value: 'apparel', label: 'Apparel' },
  { value: 'kitchenware', label: 'Kitchenware' },
  { value: 'tabletop', label: 'Tabletop & Serveware' },
  { value: 'textiles', label: 'Kitchen Textiles' },
  { value: 'drinkware', label: 'Drinkware & Bar' },
  { value: 'accessories', label: 'Accessories & Gadgets' },
  { value: 'stationery', label: 'Stationery & Media' },
  { value: 'gift-kits', label: 'Gift Bundles & Kits' },
  { value: 'kids', label: 'Kids & Family' },
  { value: 'home-decor', label: 'Home & Decor' },
  { value: 'sustainable', label: 'Sustainable Line' },
  { value: 'limited', label: 'Limited / Collabs' },
];

export const products = [
  // --- Apparel ---
  {
    id: 'tee-illustrated-recipe',
    title: 'Graphic Recipe Tee',
    price: 'Rp 145.000',
    stock: 64,
    category: 'apparel',
    meta: 'Unisex • Cotton • Illustrated recipe print',
    img: '/assets/shop/Recipe Themed/Graphic Recipe Tee.png',
    alt: 'Graphic Recipe Tee',
    details: 'Soft cotton tee with an illustrated recipe print. Wash cold, inside out. Do not iron print.',
  },
  {
    id: 'apron-linen',
    title: 'Linen Apron',
    price: 'Rp 210.000',
    stock: 38,
    category: 'apparel',
    meta: 'Cross-back • Embroidered logo',
    img: '/assets/shop/Recipe Themed/Linen Apron.png',
    alt: 'Linen Apron',
    details: 'Comfortable cross-back linen apron with embroidered logo. Machine wash gentle, hang dry.',
  },
  {
    id: 'chef-jacket-branded',
    title: 'Chef Jacket (Branded)',
    price: 'Rp 380.000',
    stock: 22,
    category: 'apparel',
    meta: 'Embroidered • Breathable • Unisex',
    img: '/assets/shop/Recipe Themed/Chef Jacket Branded.png',
    alt: 'Chef jackets & polos (branded, embroidered)',
    details: 'Professional chef jacket with embroidered logo. Breathable fabric, unisex fit. Available in sizes S-XXL. Machine wash cold, tumble dry low.',
  },
  {
    id: 'hoodie-culinary-quote',
    title: 'Culinary Quote Hoodie',
    price: 'Rp 299.000',
    stock: 40,
    category: 'apparel',
    meta: 'Fleece • Unisex • Front print',
    img: '/assets/shop/Recipe Themed/Culinary Quote Hoodie.png',
    alt: 'Hoodies & sweatshirts with culinary quotes',
    details: 'Soft fleece hoodie with inspirational culinary quote printed on front. Kangaroo pocket, drawstring hood. Unisex sizing. Machine wash cold inside out.',
  },
  {
    id: 'baker-cap',
    title: 'Baker Cap',
    price: 'Rp 95.000',
    stock: 85,
    category: 'apparel',
    meta: 'Adjustable • Embroidered logo',
    img: '/assets/shop/Recipe Themed/Baker Cap.png',
    alt: 'Hats & beanies (baseball caps, baker caps)',
    details: 'Adjustable baseball cap with embroidered logo. One size fits most. Cotton twill construction. Hand wash recommended.',
  },
  {
    id: 'kitchen-socks',
    title: 'Kitchen Socks',
    price: 'Rp 49.000',
    stock: 120,
    category: 'apparel',
    meta: 'Cotton blend • Fun culinary prints',
    img: '/assets/shop/Recipe Themed/Kitchen Socks.png',
    alt: 'Kitchen socks (fun prints: herbs, veggies, utensils)',
    details: 'Fun cotton blend socks featuring culinary prints (herbs, veggies, utensils). Comfortable fit, reinforced heel and toe. Machine wash warm.',
  },
  {
    id: 'personalized-chef-polo',
    title: 'Personalized Chef Polo',
    price: 'Rp 260.000',
    stock: 30,
    category: 'apparel',
    meta: 'Custom name/role embroidery',
    img: '/assets/shop/Recipe Themed/Personalized Chef Polo.png',
    alt: 'Personalized name/role apparel (e.g., “Head Chef [Name]”)',
    details: 'Custom embroidered polo with your name and role. Allow 7-10 business days for personalization. Available in multiple colors. Machine wash cold.',
  },

  // --- Kitchenware ---
  {
    id: 'board-etched-recipe',
    title: 'Engraved Cutting Board',
    price: 'Rp 280.000',
    stock: 25,
    category: 'kitchenware',
    meta: 'Beech • Recipe-etched • 30×20 cm',
    img: '/assets/shop/Recipe Themed/Engraved Cutting Board.png',
    alt: 'Engraved Cutting Board',
    details: 'Beechwood cutting board laser-etched with a recipe. Oil occasionally to maintain finish.',
  },
  {
    id: 'utensil-set-stainless',
    title: 'Stainless Utensil Set',
    price: 'Rp 220.000',
    stock: 50,
    category: 'kitchenware',
    meta: 'Set of 6 • Heat-resistant',
    img: '/assets/shop/Recipe Themed/Stainless Utensil Set.png',
    alt: 'Utensil sets (wooden, stainless, bamboo)',
    details: 'Professional-grade stainless steel utensil set. Includes spatula, ladle, slotted spoon, pasta server, whisk, and tongs. Heat-resistant up to 400°F. Dishwasher safe.',
  },
  {
    id: 'cast-iron-skillet',
    title: 'Cast-Iron Skillet',
    price: 'Rp 340.000',
    stock: 28,
    category: 'kitchenware',
    meta: 'Pre-seasoned • 26 cm',
    img: '/assets/shop/Recipe Themed/Cast-Iron Skillet.png',
    alt: 'Pans & skillets (cast-iron style, non-stick gift sets)',
    details: 'Pre-seasoned 26cm cast-iron skillet. Perfect for stovetop and oven use. Hand wash only, dry immediately, and oil lightly after each use to maintain seasoning.',
  },
  {
    id: 'mixing-bowls-set',
    title: 'Stainless Mixing Bowls',
    price: 'Rp 199.000',
    stock: 42,
    category: 'kitchenware',
    meta: 'Nesting set of 3 • Non-slip base',
    img: '/assets/shop/Recipe Themed/Stainless Mixing Bowls.png',
    alt: 'Mixing bowls (nesting sets, ceramic, stainless)',
    details: 'Nesting set of three stainless steel mixing bowls with non-slip silicone bases. Sizes: 1.5L, 3L, 5L. Dishwasher safe, rust-resistant.',
  },
  {
    id: 'measuring-set',
    title: 'Measuring Cups & Spoons Set',
    price: 'Rp 129.000',
    stock: 75,
    category: 'kitchenware',
    meta: 'Stainless • 10 pcs',
    img: '/assets/shop/Recipe Themed/Measuring Cups & Spoons Set.png',
    alt: 'Measuring sets (cups, spoons, digital scales)',
    details: '10-piece stainless steel measuring set. Includes 4 cups (1/4, 1/3, 1/2, 1 cup) and 6 spoons (1/8, 1/4, 1/2, 1 tsp, 1/2, 1 Tbsp). Engraved measurements won\'t fade. Dishwasher safe.',
  },
  {
    id: 'storage-jars-glass',
    title: 'Glass Storage Jars',
    price: 'Rp 210.000',
    stock: 36,
    category: 'kitchenware',
    meta: 'Set of 4 • Airtight bamboo lids',
    img: '/assets/shop/Recipe Themed/Glass Storage Jars.png',
    alt: 'Storage jars & canisters (labeled, glass with lids)',
    details: 'Set of 4 glass storage jars with airtight bamboo lids. Capacities: 500ml, 750ml, 1000ml, 1500ml. Perfect for dry goods. Hand wash lids, jars are dishwasher safe.',
  },
  {
    id: 'silicone-baking-mat',
    title: 'Silicone Baking Mat',
    price: 'Rp 89.000',
    stock: 100,
    category: 'kitchenware',
    meta: 'Non-stick • 30×40 cm',
    img: '/assets/shop/Recipe Themed/Silicone Baking Mat.png',
    alt: 'Silicone baking mats & trays',
    details: 'Non-stick silicone baking mat, 30×40cm. Replaces parchment paper. Heat-resistant up to 480°F. Wash with warm soapy water, air dry flat.',
  },

  // --- Tabletop & Serveware ---
  {
    id: 'serve-platter',
    title: 'Serving Platter',
    price: 'Rp 325.000',
    stock: 18,
    category: 'tabletop',
    meta: 'Stoneware • Recipe motif',
    img: '/assets/shop/Recipe Themed/Serving Platter.png',
    alt: 'Serving Platter',
    details: 'Stoneware platter with recipe motif. Hand wash recommended.',
  },
  {
    id: 'dinner-plates-bowls',
    title: 'Dinner Plates & Bowl Set',
    price: 'Rp 420.000',
    stock: 16,
    category: 'tabletop',
    meta: '6 pcs • Recipe art pattern',
    img: '/assets/shop/Recipe Themed/Dinner Plates & Bowl Set.png',
    alt: 'Dinner plates & bowl sets (patterned with recipe art)',
    details: '6-piece ceramic dinnerware set featuring recipe art pattern. Includes 3 dinner plates and 3 bowls. Microwave and dishwasher safe. Each piece is unique.',
  },
  {
    id: 'teacup-set',
    title: 'Recipe Teacup Set',
    price: 'Rp 150.000',
    stock: 26,
    category: 'tabletop',
    meta: 'Set of 2 • “Today’s Special” print',
    img: '/assets/shop/Recipe Themed/Recipe Teacup Set.png',
    alt: 'Mugs & teacups (recipe print, “today’s special” designs)',
    details: 'Set of 2 porcelain teacups with "Today\'s Special" prints. Each cup holds 250ml. Microwave and dishwasher safe. Comes in gift-ready box.',
  },
  {
    id: 'engraved-cutlery',
    title: 'Engraved Cutlery Set',
    price: 'Rp 330.000',
    stock: 20,
    category: 'tabletop',
    meta: '16 pcs • Engraved handles',
    img: '/assets/shop/Recipe Themed/Engraved Cutlery Set.png',
    alt: 'Specialty cutlery (engraved handles)',
    details: '16-piece stainless steel cutlery set with engraved handles. Service for 4. Includes dinner forks, knives, soup spoons, and teaspoons. Dishwasher safe.',
  },
  {
    id: 'placemats-recipe',
    title: 'Recipe Placemats',
    price: 'Rp 160.000',
    stock: 48,
    category: 'tabletop',
    meta: 'Set of 4 • Wipe-clean',
    img: '/assets/shop/Recipe Themed/Recipe Placemats.png',
    alt: 'Placemats & chargers (recipe-printed or illustrated)',
    details: 'Set of 4 wipe-clean placemats featuring vintage recipe prints. Heat-resistant up to 180°F. Simply wipe with damp cloth to clean.',
  },
  {
    id: 'linen-napkins-rings',
    title: 'Linen Napkins & Rings',
    price: 'Rp 175.000',
    stock: 32,
    category: 'tabletop',
    meta: 'Set of 4 • Natural linen',
    img: '/assets/shop/Recipe Themed/Linen Napkins & Rings.png',
    alt: 'Napkin rings & linen napkins',
    details: 'Set of 4 natural linen napkins (45×45cm) with matching wooden napkin rings. Pre-washed for softness. Machine wash cold, line dry or tumble dry low.',
  },
  {
    id: 'dessert-plates',
    title: 'Dessert Plate Set',
    price: 'Rp 180.000',
    stock: 40,
    category: 'tabletop',
    meta: 'Set of 6 • 15 cm diameter',
    img: '/assets/shop/Recipe Themed/Dessert Plates.png',
    alt: 'Dessert/small-plate sets (for tastings)',
    details: 'Set of 6 porcelain dessert plates, 15cm diameter. Perfect for appetizers, desserts, or tastings. Stackable design saves space. Dishwasher and microwave safe.',
  },

  // --- Kitchen Textiles ---
  {
    id: 'tea-towel-recipe',
    title: 'Recipe Tea Towel',
    price: 'Rp 85.000',
    stock: 120,
    category: 'textiles',
    meta: '100% Cotton • Printed instructions',
    img: '/assets/shop/Recipe Themed/Recipe Tea Towel.png',
    alt: 'Recipe Tea Towel',
    details: 'Absorbent cotton towel printed with a recipe. Machine wash warm; tumble dry low.',
  },
  {
    id: 'dish-towels-printed',
    title: 'Absorbent Dish Towels',
    price: 'Rp 75.000',
    stock: 90,
    category: 'textiles',
    meta: 'Set of 2 • Printed • 100% cotton',
    img: '/assets/shop/Recipe Themed/Absorbent Dish Towels.png',
    alt: 'Dish towels (absorbent, printed)',
    details: 'Set of 2 highly absorbent cotton dish towels with culinary prints. 50×70cm each. Machine wash warm, tumble dry low. Gets softer with each wash.',
  },
  {
    id: 'mitts-pot-holders',
    title: 'Oven Mitts & Pot Holders Set',
    price: 'Rp 110.000',
    stock: 60,
    category: 'textiles',
    meta: 'Heat-resistant • Matching pair',
    img: '/assets/shop/Recipe Themed/Oven Mitts & Pot Holders Set.png',
    alt: 'Oven mitts & pot holders (matching sets)',
    details: 'Matching set of 2 oven mitts and 2 pot holders. Heat-resistant up to 450°F. Cotton exterior with silicone liner. Machine wash cold, hang dry.',
  },
  {
    id: 'table-runner-recipe',
    title: 'Recipe Table Runner',
    price: 'Rp 155.000',
    stock: 35,
    category: 'textiles',
    meta: 'Seasonal pattern • 180 cm',
    img: '/assets/shop/Recipe Themed/Recipe Table Runner.png',
    alt: 'Table runners (seasonal recipe themes)',
    details: 'Seasonal recipe-themed table runner, 180×35cm. Cotton/linen blend. Updates with each season\'s harvest. Machine wash cold, iron if needed.',
  },
  {
    id: 'cloth-napkins-patterned',
    title: 'Cloth Napkins (Patterned)',
    price: 'Rp 120.000',
    stock: 40,
    category: 'textiles',
    meta: 'Set of 4 • Reusable • Soft weave',
    img: '/assets/shop/Recipe Themed/Cloth Napkins (Patterned).png',
    alt: 'Cloth napkins (reusable, patterned)',
    details: 'Set of 4 reusable cloth napkins with culinary patterns. Soft weave cotton, 40×40cm. Eco-friendly alternative to paper. Machine wash warm.',
  },
  {
    id: 'apron-accessories',
    title: 'Apron Accessory Kit',
    price: 'Rp 69.000',
    stock: 70,
    category: 'textiles',
    meta: 'Detachable straps • Extra pocket',
    img: '/assets/shop/Recipe Themed/Apron Accessory Kit.png',
    alt: 'Apron accessories (pockets, detachable straps)',
    details: 'Upgrade your apron with detachable adjustable straps and an extra utility pocket. Universal fit for most aprons. Easy clip-on installation.',
  },
  {
    id: 'reusable-produce-bags',
    title: 'Reusable Produce Bags',
    price: 'Rp 59.000',
    stock: 90,
    category: 'textiles',
    meta: 'Set of 3 • Mesh • Drawstring',
    img: '/assets/shop/Recipe Themed/Reusable Produce Bags.png',
    alt: 'Reusable grocery/produce bags',
    details: 'Set of 3 mesh produce bags with drawstring closure. Sizes: Small, Medium, Large. See-through design for easy checkout. Machine wash, air dry.',
  },

  // --- Drinkware & Bar ---
  {
    id: 'mug-measured',
    title: 'Measured Mug',
    price: 'Rp 99.000',
    stock: 72,
    category: 'drinkware',
    meta: '12 oz • Measurement graphics',
    img: '/assets/shop/Recipe Themed/Measured Mug.png',
    alt: 'Measured Mug',
    details: '12 oz ceramic mug with measurement markings. Dishwasher and microwave safe.',
  },
  {
    id: 'tumbler-insulated',
    title: 'Insulated Tumbler',
    price: 'Rp 175.000',
    stock: 34,
    category: 'drinkware',
    meta: 'Recipe motif • 500 ml',
    img: '/assets/shop/Recipe Themed/Insulated Tumbler.png',
    alt: 'Travel tumblers & insulated bottles',
    details: 'Double-wall vacuum insulated tumbler, 500 ml. Hand wash recommended.',
  },
  {
    id: 'wine-glasses-engraved',
    title: 'Engraved Wine Glasses',
    price: 'Rp 210.000',
    stock: 30,
    category: 'drinkware',
    meta: 'Set of 2 • 350 ml',
    img: '/assets/shop/Recipe Themed/Engraved Wine Glasses.png',
    alt: 'Wine glasses & tumblers (engraved)',
    details: 'Set of 2 wine glasses with delicate recipe-themed engravings. 350ml capacity. Hand wash recommended to preserve engraving. Gift boxed.',
  },
  {
    id: 'cocktail-shaker-set',
    title: 'Cocktail Shaker Set',
    price: 'Rp 240.000',
    stock: 22,
    category: 'drinkware',
    meta: 'Shaker • Strainer • Jigger',
    img: '/assets/shop/Recipe Themed/Cocktail Shaker Set.png',
    alt: 'Cocktail shakers & bar tools',
    details: 'Complete bartending set: 750ml shaker, Hawthorne strainer, double jigger (25ml/50ml). Professional-grade stainless steel. Hand wash and dry immediately.',
  },
  {
    id: 'coaster-set-recipe',
    title: 'Recipe Coaster Set',
    price: 'Rp 89.000',
    stock: 80,
    category: 'drinkware',
    meta: 'Set of 6 • Cork-backed',
    img: '/assets/shop/Recipe Themed/Recipe Coaster Set.png',
    alt: 'Coaster sets (recipe snippets or ingredient illustrations)',
    details: 'Set of 6 coasters featuring recipe snippets and ingredient illustrations. Cork-backed to protect surfaces. Wipe clean with damp cloth.',
  },
  {
    id: 'infuser-bottle',
    title: 'Fruit Infuser Bottle',
    price: 'Rp 130.000',
    stock: 55,
    category: 'drinkware',
    meta: '700 ml • BPA-free',
    img: '/assets/shop/Recipe Themed/Fruit Infuser Bottle.png',
    alt: 'Infuser/fruit water bottles',
    details: '700ml BPA-free water bottle with removable fruit infuser basket. Leak-proof lid. Perfect for infused water, tea, or juice. Hand wash recommended.',
  },
  {
    id: 'bottle-opener-stopper',
    title: 'Branded Bottle Opener & Stopper',
    price: 'Rp 99.000',
    stock: 70,
    category: 'drinkware',
    meta: 'Steel opener • Silicone stopper',
    img: '/assets/shop/Recipe Themed/Branded Bottle Opener & Stopper.png',
    alt: 'Bottle openers & stoppers (branded)',
    details: 'Stainless steel bottle opener with branded logo plus silicone wine stopper. Compact design. The stopper creates an airtight seal. Hand wash.',
  },

  // --- Accessories & Gadgets ---
  {
    id: 'magnetic-recipe-clips',
    title: 'Magnetic Recipe Clips',
    price: 'Rp 59.000',
    stock: 150,
    category: 'accessories',
    meta: 'Set of 6 • Fridge-safe',
    img: '/assets/shop/Recipe Themed/Magnetic Recipe Clips.png',
    alt: 'Magnetic fridge recipe clips',
    details: 'Set of 6 strong magnetic clips for holding recipe cards or notes on your fridge. Each clip holds up to 10 sheets. Various culinary designs.',
  },
  {
    id: 'spice-grinder',
    title: 'Spice Grinder Mill',
    price: 'Rp 115.000',
    stock: 60,
    category: 'accessories',
    meta: 'Adjustable grind • Ceramic core',
    img: '/assets/shop/Recipe Themed/Spice Grinder.png',
    alt: 'Spice grinders & mills',
    details: 'Adjustable ceramic core spice grinder. From fine to coarse settings. Easy to refill. Stainless steel and glass construction. Wipe clean exterior.',
  },
  {
    id: 'herb-scissors-peeler',
    title: 'Herb Scissors & Peeler',
    price: 'Rp 99.000',
    stock: 75,
    category: 'accessories',
    meta: '5-blade scissors • Y-peeler',
    img: '/assets/shop/Recipe Themed/Herb Scissors & Peeler.png',
    alt: 'Herb scissors & peelers',
    details: '5-blade herb scissors for quick chopping plus ergonomic Y-peeler. Scissors have safety cover. Stainless steel blades. Dishwasher safe.',
  },
  {
    id: 'silicone-spatula',
    title: 'Silicone Spatula',
    price: 'Rp 49.000',
    stock: 140,
    category: 'accessories',
    meta: 'Heat-resistant • Quote print',
    img: '/assets/shop/Recipe Themed/Silicone Spatula.png',
    alt: 'Silicone spatulas & turners (logo/quote variants)',
    details: 'Heat-resistant silicone spatula with inspirational quote. Safe up to 450°F. Won\'t scratch non-stick surfaces. Dishwasher safe.',
  },
  {
    id: 'citrus-zester',
    title: 'Citrus Zester',
    price: 'Rp 59.000',
    stock: 90,
    category: 'accessories',
    meta: 'Stainless steel • Fine grate',
    img: '/assets/shop/Recipe Themed/Citrus Zester.png',
    alt: 'Citrus zesters & graters',
    details: 'Sharp stainless steel zester for citrus peels, hard cheese, chocolate, and more. Ergonomic handle. Includes protective blade cover. Dishwasher safe.',
  },
  {
    id: 'digital-thermometer',
    title: 'Digital Kitchen Thermometer',
    price: 'Rp 99.000',
    stock: 65,
    category: 'accessories',
    meta: 'Instant read • Backlit display',
    img: '/assets/shop/Recipe Themed/Digital Kitchen Thermometer.png',
    alt: 'Egg timers & digital thermometers',
    details: 'Instant-read digital thermometer with backlit display. Temperature range: -50°C to 300°C. Auto-off feature. Includes battery. Wipe clean probe after use.',
  },
  {
    id: 'recipe-card-box',
    title: 'Recipe Card Box',
    price: 'Rp 135.000',
    stock: 40,
    category: 'accessories',
    meta: 'Holds 4x6 cards • Dividers included',
    img: '/assets/shop/Recipe Themed/Recipe Card Box.png',
    alt: 'Recipe card boxes (desktop)',
    details: 'Desktop recipe card organizer holds 4×6 inch cards. Includes 6 category dividers. Bamboo construction with magnetic closure. Wipe with damp cloth.',
  },

  // --- Stationery & Media ---
  {
    id: 'recipe-cards-blank',
    title: 'Blank Recipe Cards',
    price: 'Rp 55.000',
    stock: 200,
    category: 'stationery',
    meta: 'Pack of 24 • 4x6 in • Heavy stock',
    img: '/assets/shop/Recipe Themed/Recipe Cards Blank.png',
    alt: 'Blank recipe cards',
    details: 'Heavy stock 4x6 recipe cards in a 24-pack. Lines and section prompts included.',
  },
  {
    id: 'mini-cookbooklet',
    title: 'Mini Cookbooklet',
    price: 'Rp 49.000',
    stock: 80,
    category: 'stationery',
    meta: '12-page recipe zine',
    img: '/assets/shop/Recipe Themed/Mini Cookbooklet.png',
    alt: 'Printed cookbooklets (mini collections)',
    details: 'A 12-page zine of themed recipes. Printed on recycled paper.',
  },
  {
    id: 'meal-planner-pad',
    title: 'Weekly Meal Planner Pad',
    price: 'Rp 69.000',
    stock: 90,
    category: 'stationery',
    meta: '50 sheets • Perforated tear-off',
    img: '/assets/shop/Recipe Themed/Weekly Meal Planner Pad.png',
    alt: 'Meal planners & weekly menu pads',
    details: '50-sheet tear-off pad for weekly meal planning. Includes shopping list section. Perforated for easy removal. Magnetic backing to stick on fridge.',
  },
  {
    id: 'grocery-list-pad',
    title: 'Grocery List Pad',
    price: 'Rp 49.000',
    stock: 110,
    category: 'stationery',
    meta: 'Magnetic back • 60 sheets',
    img: '/assets/shop/Recipe Themed/Grocery List Pad.png',
    alt: 'Grocery list pads & pantry inventory sheets',
    details: '60-sheet grocery list pad with categories (produce, dairy, pantry, etc.). Magnetic backing for fridge. Check-box format for easy shopping.',
  },
  {
    id: 'kitchen-poster',
    title: 'Kitchen Poster (Illustrated Recipe)',
    price: 'Rp 135.000',
    stock: 50,
    category: 'stationery',
    meta: 'A3 • Matte • Frame-ready',
    img: '/assets/shop/Recipe Themed/Kitchen Poster (Illustrated Recipe).png',
    alt: 'Kitchen wall prints/posters (illustrated recipes)',
    details: 'A3 matte poster featuring beautifully illustrated recipe. Printed on archival-quality paper. Frame-ready. Multiple recipe designs available.',
  },
  {
    id: 'sticker-label-set',
    title: 'Jar Label Stickers',
    price: 'Rp 39.000',
    stock: 160,
    category: 'stationery',
    meta: 'Waterproof • 80 labels',
    img: '/assets/shop/Recipe Themed/Jar Label Stickers.png',
    alt: 'Stickers & labels (for jars, gifts)',
    details: '80 waterproof jar labels for pantry organization. Pre-printed common ingredients plus blanks for custom labeling. Removable adhesive won\'t leave residue.',
  },

  // --- Gift Bundles & Kits ---
  {
    id: 'baking-starter-kit',
    title: 'Baking Starter Kit',
    price: 'Rp 375.000',
    stock: 20,
    category: 'gift-kits',
    meta: 'Measuring set • Spatula • Cards',
    img: '/assets/shop/Recipe Themed/Baking Starter Kit.png',
    alt: 'Baking kit',
    details: 'Gift-ready kit including measuring cups, spatula, and recipe cards. Perfect for beginners.',
  },
  {
    id: 'beginner-cook-kit',
    title: 'Beginner Cook Starter Kit',
    price: 'Rp 430.000',
    stock: 18,
    category: 'gift-kits',
    meta: 'Utensils • Apron • Recipe cards',
    img: '/assets/shop/Recipe Themed/Beginner Cook Starter Kit.png',
    alt: 'Beginner cook starter kit (utensils + apron + cards)',
    details: 'Complete beginner kit includes: linen apron, 6-piece utensil set, measuring cups/spoons, and 20 basic recipe cards. Beautifully packaged for gifting.',
  },
  {
    id: 'brunch-bundle',
    title: 'Brunch Bundle',
    price: 'Rp 210.000',
    stock: 24,
    category: 'gift-kits',
    meta: 'Pancake mix • Syrup • Recipe card',
    img: '/assets/shop/Recipe Themed/Brunch Bundle.png',
    alt: 'Brunch bundle (pancake mix + syrup bottle + recipe card)',
    details: 'Everything for the perfect brunch: artisanal pancake mix (500g), maple syrup (250ml), branded syrup bottle, and illustrated recipe card. Gift wrapped.',
  },
  {
    id: 'grilling-essentials',
    title: 'Grilling Essentials Set',
    price: 'Rp 320.000',
    stock: 14,
    category: 'gift-kits',
    meta: 'Spatula • Dry rubs • Booklet',
    img: '/assets/shop/Recipe Themed/Grilling Essentials Set.png',
    alt: 'Grilling essentials set (spatula, rubs, recipe booklet)',
    details: 'Grilling kit includes: heavy-duty spatula, 3 signature dry rub blends (100g each), grilling recipe booklet, and branded apron. Perfect for BBQ season.',
  },
  {
    id: 'tasting-kit',
    title: 'Tea & Coffee Tasting Kit',
    price: 'Rp 240.000',
    stock: 20,
    category: 'gift-kits',
    meta: 'Sampler • Tasting notes • Mug',
    img: '/assets/shop/Recipe Themed/Tea & Coffee Tasting Kit.png',
    alt: 'Tea/coffee tasting kit (samples + mug)',
    details: 'Curated sampler of 6 teas and 6 coffee varieties. Includes tasting notes guide and branded ceramic mug. Discover your new favorite brew.',
  },
  {
    id: 'holiday-gift-box',
    title: 'Seasonal Holiday Gift Box',
    price: 'Rp 290.000',
    stock: 18,
    category: 'gift-kits',
    meta: 'Themed recipes • Festive decor',
    img: '/assets/shop/Recipe Themed/Seasonal Holiday Gift Box.png',
    alt: 'Seasonal holiday gift box (themed recipes + decor)',
    details: 'Limited edition holiday box with seasonal recipe cards, festive tea towel, scented candle, cookie cutters, and decorative items. Changes with each holiday season.',
  },
  {
    id: 'subscription-box',
    title: 'Monthly Recipe Subscription Box',
    price: 'Rp 199.000',
    stock: 'Available',
    category: 'gift-kits',
    meta: '1 recipe • Curated merch • Monthly',
    img: '/assets/shop/Recipe Themed/Monthly Recipe Subscription Box.png',
    alt: 'Subscription box (monthly recipe + curated merch)',
    details: 'Receive a new themed recipe each month plus curated merch items. Cancel anytime. First box ships within 5 business days. Great for continuous culinary inspiration.',
  },

  // --- Kids & Family ---
  {
    id: 'kids-apron-hat',
    title: 'Kids Apron & Chef Hat',
    price: 'Rp 155.000',
    stock: 44,
    category: 'kids',
    meta: 'Ages 4–9 • Adjustable',
    img: '/assets/shop/Recipe Themed/Kids Apron & Chef Hat.png',
    alt: 'Kids’ aprons & chef hats',
    details: 'Adjustable kids apron with matching hat. Machine wash gentle; hang dry.',
  },
  {
    id: 'kids-utensils-bake',
    title: 'Kids Utensils & Bake Set',
    price: 'Rp 120.000',
    stock: 50,
    category: 'kids',
    meta: 'Silicone • Child-safe • Colorful',
    img: '/assets/shop/Recipe Themed/Kids Utensils & Bake Set.png',
    alt: 'Child-sized utensils & silicone bake sets',
    details: 'Child-safe silicone baking tools in fun colors. Includes spatula, whisk, measuring spoons, and mini rolling pin. BPA-free, dishwasher safe. Ages 4+.',
  },
  {
    id: 'family-recipe-journal',
    title: 'Family Recipe Journal',
    price: 'Rp 150.000',
    stock: 44,
    category: 'kids',
    meta: 'Hardcover • Guided prompts',
    img: '/assets/shop/Recipe Themed/Family Recipe Journal.png',
    alt: 'Family recipe journal (to record handed-down recipes)',
    details: 'Hardcover journal for recording family recipes and memories. Guided prompts for recipe details, photos, and stories. Acid-free paper. A treasured heirloom.',
  },
  {
    id: 'kids-activity-cards',
    title: 'Kids Cooking Activity Cards',
    price: 'Rp 89.000',
    stock: 60,
    category: 'kids',
    meta: '30 cards • Step-by-step',
    img: '/assets/shop/Recipe Themed/Kids Cooking Activity Cards.png',
    alt: 'Kids’ cooking activity cards (simple recipes)',
    details: '30 illustrated recipe cards with simple, kid-friendly recipes. Step-by-step photos. Safety tips included. Laminated for durability. Ages 6-12.',
  },
  {
    id: 'kids-stickers-flashcards',
    title: 'Food Stickers & Flashcards',
    price: 'Rp 69.000',
    stock: 100,
    category: 'kids',
    meta: '60 stickers • 20 flashcards',
    img: '/assets/shop/Recipe Themed/Food Stickers & Flashcards.png',
    alt: 'Educational food stickers & flashcards',
    details: 'Educational set with 60 food-themed stickers and 20 flashcards teaching fruits, vegetables, and kitchen tools. Perfect for early learners. Ages 3+.',
  },
  {
    id: 'kids-story-book',
    title: 'Story Recipe Picture Book',
    price: 'Rp 99.000',
    stock: 38,
    category: 'kids',
    meta: 'Full color • 32 pages',
    img: '/assets/shop/Recipe Themed/Story Recipe Picture Book.png',
    alt: 'Story/recipe picture books (digital/printed)',
    details: '32-page full-color picture book combining storytelling with simple recipes. Characters learn cooking skills through adventure. Hardcover, ages 4-8.',
  },
  {
    id: 'silicone-bibs-mats',
    title: 'Silicone Bibs & Spill Mats',
    price: 'Rp 79.000',
    stock: 70,
    category: 'kids',
    meta: 'BPA-free • Easy clean',
    img: '/assets/shop/Recipe Themed/Silicone Bibs & Spill Mats.png',
    alt: 'Silicone bibs & spill mats',
    details: 'Set includes baby bib with food-catching pocket and placemat with suction cups. BPA-free silicone. Dishwasher safe. Fun food illustrations.',
  },

  // --- Home & Decor ---
  {
    id: 'wall-art-recipe',
    title: 'Recipe Wall Art',
    price: 'Rp 120.000',
    stock: 60,
    category: 'home-decor',
    meta: 'A4 Print • Matte • Frame-ready',
    img: '/assets/shop/Recipe Themed/Recipe Wall Art.png',
    alt: 'Kitchen wall prints/posters (illustrated recipes)',
    details: 'A4 art print featuring vintage-style recipe illustration. Matte finish on premium paper. Fits standard frames. Multiple designs available to mix and match.',
  },
  {
    id: 'kitchen-magnet-set',
    title: 'Kitchen Magnet Set',
    price: 'Rp 39.000',
    stock: 140,
    category: 'home-decor',
    meta: 'Set of 5 • Mini recipe icons',
    img: '/assets/shop/Recipe Themed/Kitchen Magnet Set.png',
    alt: 'Kitchen magnets (mini recipe magnets)',
    details: 'Set of five magnets with mini recipe icons. Strong hold, glossy finish.',
  },
  {
    id: 'tapestry-art',
    title: 'Recipe Tapestry Art',
    price: 'Rp 220.000',
    stock: 28,
    category: 'home-decor',
    meta: 'Wall-hanging • Woven texture',
    img: '/assets/shop/Recipe Themed/Recipe Tapestry Art.png',
    alt: 'Recipe tapestry/tea-towel framed art',
    details: 'Woven wall-hanging featuring recipe in artistic typography. Includes wooden hanging rod. Machine wash gentle, hang to dry. Adds warmth to any kitchen.',
  },
  {
    id: 'throw-pillow-culinary',
    title: 'Culinary Quote Throw Pillow',
    price: 'Rp 150.000',
    stock: 40,
    category: 'home-decor',
    meta: '45×45 cm • Removable cover',
    img: '/assets/shop/Recipe Themed/Culinary Quote Throw Pillow.png',
    alt: 'Throw pillows with culinary quotes or prints',
    details: '45×45cm throw pillow with culinary quote print. Removable, machine-washable cover. Soft polyester fill. Hidden zipper closure. Adds personality to any space.',
  },
  {
    id: 'spice-rack-wall',
    title: 'Wall-Mounted Spice Rack',
    price: 'Rp 260.000',
    stock: 22,
    category: 'home-decor',
    meta: 'Bamboo • 3 tiers • Hardware incl.',
    img: '/assets/shop/Recipe Themed/Wall-Mounted Spice Rack.png',
    alt: 'Wall-mounted spice racks (decorative)',
    details: '3-tier bamboo spice rack for wall mounting. Holds 24+ standard spice jars. All mounting hardware included. Easy assembly. Sustainable bamboo construction.',
  },
  {
    id: 'vintage-recipe-print',
    title: 'Framed Vintage Recipe Print',
    price: 'Rp 230.000',
    stock: 18,
    category: 'home-decor',
    meta: 'A4 • Limited edition frame',
    img: '/assets/shop/Recipe Themed/Framed Vintage Recipe Print.png',
    alt: 'Framed vintage recipe prints (limited)',
    details: 'Limited edition A4 vintage recipe print in quality wood frame. Numbered and signed. Ready to hang. Only 100 of each design produced. Comes with certificate.',
  },
  {
    id: 'scented-candle-bakery',
    title: 'Bakery Scented Candle',
    price: 'Rp 99.000',
    stock: 60,
    category: 'home-decor',
    meta: 'Soy wax • Vanilla & cinnamon',
    img: '/assets/shop/Recipe Themed/Bakery Scented Candle.png',
    alt: 'Scented candles “bakery/kitchen” series',
    details: 'Hand-poured soy wax candle with vanilla & cinnamon fragrance. 40-hour burn time. Lead-free cotton wick. Comes in reusable glass jar. Made with natural ingredients.',
  },
  {
    id: 'ceramic-herb-planter',
    title: 'Ceramic Herb Planter',
    price: 'Rp 120.000',
    stock: 38,
    category: 'home-decor',
    meta: 'Drainage hole • Saucer included',
    img: '/assets/shop/Recipe Themed/Ceramic Herb Planter.png',
    alt: 'Ceramic planters for kitchen herbs',
    details: 'Hand-glazed ceramic planter perfect for kitchen herbs. Drainage hole with matching saucer. 15cm diameter. Grow fresh basil, mint, or parsley at home.',
  },

  // --- Sustainable Line ---
  {
    id: 'beeswax-wraps',
    title: 'Beeswax Food Wraps',
    price: 'Rp 110.000',
    stock: 90,
    category: 'sustainable',
    meta: 'Set of 3 • Recipe pattern',
    img: '/assets/shop/Recipe Themed/Beeswax Food Wraps.png',
    alt: 'Beeswax food wraps with recipe patterns',
    details: 'Reusable wraps with recipe patterns. Hand wash in cool water with mild soap. Air dry.',
  },
  {
    id: 'reusable-sandwich-bags',
    title: 'Reusable Sandwich Bags',
    price: 'Rp 89.000',
    stock: 80,
    category: 'sustainable',
    meta: 'Set of 3 • Zip-seal • Printed',
    img: '/assets/shop/Recipe Themed/Reusable Sandwich Bags.png',
    alt: 'Reusable sandwich/snack bags (printed)',
    details: 'Set of 3 food-safe reusable bags with zip-seal closures. BPA-free, lead-free. Printed with fun culinary designs. Hand wash recommended. Reduces single-use plastic.',
  },

  // --- Limited / Collabs ---
  {
    id: 'enamel-pin-collectible',
    title: 'Collectible Enamel Pin',
    price: 'Rp 65.000',
    stock: 40,
    category: 'limited',
    meta: 'Limited run • Numbered',
    img: '/assets/shop/Recipe Themed/CollectibleEnamelPin.png',
    alt: 'Collectible enamel pins (food icons)',
    details: 'Limited run enamel pin. Keep dry; avoid chemicals. Backer card included.',
  },
];