export const dessertRecipes = [
  {
    id: "chocolate-cake",
    name: "Chocolate Sheet Cake",
    prepTime: "20 mins",
    cookTime: "30 mins",
    totalTime: "50 mins",
    difficulty: "Easy",
    rating: 4.5,
    reviews: 50,
    image: "../../assets/desserts/Chocolate Sheet Cake.jpg",
    description: "This incredible chocolate cake recipe is just as easy to make as a boxed cake mix. It's crazy moist and super delicious. The luscious chocolate frosting is silky-smooth and creamy.",
    ingredients: [
      "1 3/4 cups (228g) all purpose flour",
      "2 cups (400g) granulated sugar",
      "3/4 cup (85g) natural unsweetened cocoa powder",
      "2 1/4 tsp baking soda",
      "1/2 tsp baking powder",
      "1 teaspoon salt",
      "1 cup (240ml) milk",
      "1/2 cup (120ml) vegetable oil",
      "1 1/2 teaspoon vanilla extract",
      "2 large eggs",
      "1 cup (240ml) hot water",
      "1 cup (227g) unsalted butter",
      "4 cups (500g) powdered sugar",
      "4-6 tablespoons milk or cream",
      "1/2 cup (57g) natural unsweetened cocoa powder",
      "1 teaspoon vanilla extract",
      "Sprinkles"
    ],
    instructions: [
      { step: "", details: ["Preheat oven to 350F and grease a 9×13″ baking pan with non-stick baking spray or butter.", "In a large bowl, whisk together the flour, sugar, cocoa powder, baking soda, baking powder and salt. Set aside.", "In a medium bowl, whisk together the milk, vegetable oil, vanilla and eggs.", "Add the wet ingredients to the dry ingredients and mix until combined with a rubber spatula.", "Add in the hot water and whisk until smooth.", "Pour into the prepared baking pan and bake for 30-32 minutes or until a toothpick inserted into the center comes out with a few moist crumbs.", "Let cool completely before frosting.", "Using a handheld or stand mixer, beat the butter for 1 minute until creamy. Mix in 1 cup of powder sugar and with 1 tbsp of milk/cream at a time, mixing well in between.", "Mix in the cocoa powder and vanilla until smooth. Add more milk/cream if necessary for a spreadable consistency."] }
    ],
    nutrition: {
      calories: 307,
      carbs: "47g",
      protein: "3g",
      fat: "14g",
      saturatedFat: "6g",
      transFat: "0g",
      cholesterol: "35mg",
      sodium: "222mg",
      potassium: "106mg",
      fiber: "2g",
      sugar: "37g",
      vitaminA: "277IU",
      calcium: "33mg",
      iron: "1mg"
    },
    tags: ["Dessert", "Chocolate", "Easy", "Family Favorite", "Best for Birthday"],
    video: "https://www.youtube.com/embed/VRFhLCyDSJk?si=czWlOhYDJ3lkBEcu"
  },
  {
    id: "blueberry-cake",
    name: "Blueberry Heaven on Earth Cake",
    prepTime: "30 mins",
    waitTime: "4 hrs",
    totalTime: "4 hrs 30 mins",
    difficulty: "Medium",
    rating: 5,
    reviews: 206,
    image: "../../assets/desserts/Blueberry Heaven on Earth Cake.jpg",
    description: "This blueberry heaven on earth cake truly lives up to its name, featuring moist cake, a delightful homemade blueberry pie filling, two luscious creams, and toasted almonds to top it off!",
    ingredients: [
      "240g (1 cup) whole milk 3% fat",
      "50g (1/4 cups) granulated sugar",
      "40g egg yolk",
      "12g (1 1/2 tablespoon) corn starch",
      "12g (1 1/2 tablespoon) all purpose flour",
      "1 teaspoon vanilla extract",
      "28g (2 tablespoons) unsalted butter",
      "115g (1/2 cups) heavy cream",
      "230g (1 cup) heavy cream",
      "75g (1/3 cups) mascarpone",
      "30g (1/4 cups) powdered sugar",
      "1/2 teaspoon vanilla extract",
      "600g (21 ounce) blueberry pie filling",
      "400g (14 ounce) angel food cake",
      "Toasted almond slivers"
    ],
    instructions: [
      { step: "Luxurious Vanilla Cream Layer", details: ["Whisk the sugar and egg yolks until fluffy, then mix in the cornstarch, flour, and vanilla until you get a smooth paste.", "Heat the milk until simmering, then slowly pour it over the egg mixture while whisking vigorously. Return the mixture to the saucepan and cook for a few minutes until thickened.", "Gradually stir in the softened butter until fully incorporated. The pastry cream needs to completely cool before folding the heavy cream in. Cover it with plastic wrap to prevent skin from forming.", "Once cooled, whisk the pastry cream for 1-2 minutes to get a smooth texture. Make sure you do not over-whisk it, as it can get runny. Give it a few whisks only until smooth.", "Whip the very cold heavy cream to soft peaks. Gently fold the whipped cream into the pastry cream in three stages, mixing carefully after each addition. Refrigerate your vanilla cream layer while preparing the rest of the layers."] },
      { step: "Chantilly Whipped Cream Layer", details: ["Using an electric hand mixer, whip the very cold heavy cream, mascarpone, and sifted powdered sugar for about a minute, then add the vanilla extract.", "Continue whipping for 2 to 3 minutes, or until the cream reaches a fluffy, pipeable consistency (after soft peaks but before stiff peaks). Be sure to stop whipping right away to avoid over-beating. If you continue, the chantilly cream will separate and become runny."] },
      { step: "Blueberry Layer", details: ["Open a tin of blueberry pie filling can or prepare it from scratch using my recipe."] },
      { step: "Assembly", details: ["Layer the Blueberry Heaven on Earth cake from the bottom to top (1/2 blueberry filling layer minus three tablespoons that will go to the top, 1/2 vanilla layer, whipped cream layer and the three tablespoons of blueberry pie filling swirled into it). Make sure to spread the layers evenly in the pan, smoothing each level with an offset spatula before adding the next.", "Refrigerate for 4 hours for the cake to set. Just before serving, add some toasted almond slivers on top.", "Store leftovers in an airtight container in the refrigerator for up to 2 days."] }
    ],
    nutrition: {
      calories: 366,
      carbs: "52g",
      protein: "5g",
      fat: "17g",
      saturatedFat: "10g",
      transFat: "0g",
      cholesterol: "82mg",
      sodium: "197mg",
      potassium: "166mg",
      fiber: "1g",
      sugar: "35g",
      vitaminC: "1mg",
      vitaminA: "660IU",
      calcium: "99mg",
      iron: "1mg"
    },
    tags: ["Dessert", "Blueberry", "Sweet", "Party"],
    video: "https://www.youtube.com/embed/D6MUFiwL0UE?si=BPdZCVnJH3ekqOx9"
  },
  {
    id: "boston-cake",
    name: "Boston Cream Poke Cake",
    prepTime: "20 mins",
    cookTime: "30 mins",
    totalTime: "50 mins",
    difficulty: "Easy",
    rating: 5,
    reviews: 22,
    image: "../../assets/desserts/Boston Cream Poke Cake.jpg",
    description: "This Boston cream poke cake is a fun variation of a Boston cream pie. Made with boxed cake and instant pudding mixes, this super easy dessert is sure to be a hit with family and friends.",
    ingredients: [
      "1 (15.25 ounce) package yellow cake mix",
      "1 cup water",
      "3 large eggs",
      "1/4 cup vegetable oil",
      "4 cups milk",
      "2 (3.5 ounce) packages instant vanilla pudding mix",
      "2 cups semisweet chocolate chips",
      "1 cup heavy whipping cream"
    ],
    instructions: [
      { step: "", details: ["Preheat the oven to 350 degrees F (175 degrees C). Grease a 9x13-inch pan.", "Beat cake mix, water, eggs, and oil in a large bowl with an electric mixer until combined. Pour batter into the prepared pan.", "Bake in the preheated oven until a toothpick inserted into the center comes out clean, about 30 minutes. Let cool for 15 to 30 minutes.", "Whisk milk and pudding mix together in a bowl until just starting to thicken. Poke holes all over cake with the handle of a wooden spoon. Pour pudding mixture over cake, and spread over entire surface to fill the holes. Refrigerate until firm, about 1 hour.", "When the cake is almost firm, place chocolate chips into a glass bowl.", "Heat cream in a small saucepan over medium-low heat, stirring frequently, until bubbles form, about 3 minutes. Pour hot cream over chocolate chips (whisk until smooth).", "Spread ganache over cake."] }
    ],
    nutrition: {
      calories: 386,
      carbs: "49g",
      protein: "5g",
      fat: "20g",
      saturatedFat: "9g",
      transFat: "0g",
      cholesterol: "57mg",
      sodium: "399mg",
      potassium: "214mg",
      fiber: "2g",
      sugar: "35g",
      vitaminC: "0mg",
      calcium: "131mg",
      iron: "1mg"
    },
    tags: ["Dessert", "Boston", "Chocolate", "Easy", "Family Favorite"],
    video: "https://www.youtube.com/embed/0sAQufFPHfQ?si=40l9E4VZNVTCcsXT"
  },
  {
    id: "lemon-ricotta-cake",
    name: "Italian Lemon Ricotta Cake",
    prepTime: "12 mins",
    cookTime: "55 mins",
    totalTime: "1 hr 7 mins",
    difficulty: "Medium",
    rating: 4.5,
    reviews: 301,
    image: "../../assets/desserts/Italian Lemon Ricotta Cake.jpeg",
    description: "This Italian Lemon Ricotta Cake is light, fluffy, and full of flavor. Made with ricotta cheese and fresh lemon, you're going to love this traditional Italian dessert that's also great served as a breakfast or brunch treat.",
    ingredients: [
      "3/4 cup butter, softened 1 1/2 sticks",
      "1 1/2 cups sugar",
      "15 ounces whole milk ricotta cheese",
      "3 large eggs",
      "1 teaspoon vanilla",
      "1 large lemon, zested and juiced",
      "1/2 teaspoon baking soda",
      "1/2 teaspoon salt",
      "1 1/2 cups flour",
      "Powdered sugar for dusting top of cake"
    ],
    instructions: [
      { step: "", details: ["Preheat oven to 350 degrees. Grease a 9 inch springform pan using butter and powdered sugar, set aside.", "In a large mixing bowl or stand up mixer, cream together the butter and sugar until combined. Add in the ricotta cheese and blend until light and fluffy, about 4 to 5 minutes.", "Mix in the eggs, one at a time. Add in the vanilla, lemon zest, and lemon juice and mix to combine. In the same bowl, stir in the baking soda and salt. Lastly, add in the flour and mix until just combined, scraping down the sides of bowl to full incorporate all of the ingredients.", "Pour the batter into the prepared springform pan. Bake for 45-55 minutes, or until the cake is set and a toothpick inserted in the middle of the cake comes out clean.", "Let cool in pan for 15 minutes before removing the collar and base of the pan. Cool on a wire rack and dust with powdered sugar before serving."] }
    ],
    nutrition: {
      calories: 501,
      carbs: "57g",
      protein: "11g",
      fat: "26g",
      saturatedFat: "16g",
      transFat: "1g",
      cholesterol: "134mg",
      sodium: "285mg",
      fiber: "1g",
      sugar: "38g",
      iron: "2mg",
      vitaminC: "2mg",
      vitaminA: "858IU"
    },
    tags: ["Cake", "Lemon Ricotta", "Lemony Flavor", "Easy", "Family Favorite"],
    video: "https://www.youtube.com/embed/chym-6Nr2tM?si=qjPdamWF0vXTW2jb"
  },
  {
    id: "limoncello-tiramisu",
    name: "Limoncello Tiramisu",
    prepTime: "25 mins",
    coolingTime: "4 hrs",
    totalTime: "4 hrs 25 mins",
    difficulty: "Medium",
    rating: 3.5,
    reviews: 198,
    image: "../../assets/desserts/Limoncello Tiramisu.jpg",
    description: "Limoncello Tiramisu is a simple make-ahead Italian dessert made with Limoncello liqueur, mascarpone cheese, and ladyfinger cookies. This is a deliciously lemony version of classic Italian tiramisu and can be made up to two days in advance.",
    ingredients: [
      "2 cups mascarpone cheese",
      "1/4 cup Lemon Curd",
      "1/4 cup Limoncello",
      "1 lemon, zested and juiced",
      "2 cups heavy whipping cream",
      "1/3 cup powdered sugar",
      "3/4 cup sugar",
      "4 lemons, zested and juiced",
      "1/2 cup Lemon Curd",
      "1 tablespoon Limoncello (optional)"
    ],
    instructions: [
      { step: "", details: ["In a large bowl using a handheld mixer, beat together the mascarpone, 1/4 cup lemon curd, 1/4 cup Limoncello, and the juice and zest of one lemon. Set aside.", "In another bowl using a handheld mixer, beat together the heavy whipping cream and powdered sugar until mixture thickens into peaks.", "Use a rubber spatula to gently fold the whipped cream mixture into the mascarpone mixture, set aside.", "To make the soak, bring sugar and the juice and zest of four lemons to a boil. Reduce to a simmer and cook for 2 minutes. Turn off the heat and pour in 1/2 cup Limoncello.", "To assemble, take the ladyfingers and quickly dip them in the soak mixture, allowing them to soak up some the liquid. Repeat with half of the ladyfingers laying them to fit in the bottom of the baking pan, cutting to fit if necessary. (You will have leftover soak).", "Gently scoop on half of the mascarpone mixture and spread over the ladyfingers. Repeat the layers with the remaining soaked ladyfingers, ending with the other half of the mascarpone filling.", "To make the drizzle, thin out 1/4 cup of lemon curd with either a tablespoon of Limoncello, or remaining soak. Whisk and then carefully drizzle over top of the tiramisu.", "Cover and refrigerate for at least 4 hours or up to two days before serving."] }
    ],
    nutrition: {
      calories: 438,
      carbs: "40g",
      protein: "6g",
      fat: "26g",
      saturatedFat: "16g",
      transFat: "0.01g",
      sodium: "82mg",
      potassium: "103mg",
      fiber: "1g",
      sugars: "22g",
      vitaminA: "976IU",
      vitaminC: "18mg",
      calcium: "80mg"
    },
    tags: ["Dessert", "Limoncello", "Tiramisu", "Easy", "Perfect for Party"],
    video: "https://www.youtube.com/embed/79fHqGywovs?si=s_lJ1NmY_4SUCKwp"
  },
  {
    id: "strawberry-tiramisu",
    name: "Strawberry Tiramisu",
    prepTime: "15 mins",
    chillTime: "12 hrs",
    totalTime: "12 hrs 15 mins",
    difficulty: "Easy",
    rating: 4.5,
    reviews: 53,
    image: "../../assets/desserts/Strawberry Tiramisu.jpg",
    description: "Strawberry Tiramisu is a delicious twist on the classic dessert. Made with no raw eggs, this is a simple and delicious treat to have on hand for any occasion.",
    ingredients: [
      "1 cup heavy whipping cream",
      "1/2 cup powdered sugar",
      "1 teaspoon vanilla",
      "8 ounces mascarpone cheese, softened",
      "1/2 cup strawberry jam, seedless",
      "1/4 cup Grand Marnier",
      "1/4 cup water",
      "1 package ladyfingers",
      "1 pound strawberries, sliced",
      "Powdered sugar for sprinkling"
    ],
    instructions: [
      { step: "", details: ["In a large bowl, use a handheld mixer to beat the heavy cream, powdered sugar, and vanilla until stiff peaks form. Fold in the mascarpone and mix until well combined.", "In a separate bowl, whisk together the strawberry jam, Grand Marnier (if using), and water. Dip half of the ladyfingers in the mixture and arrange them in a single layer in the bottom of a 9 x 9 inch baking dish.", "Spoon half of the mascarpone mixture over the ladyfingers, spreading it evenly. Arrange half of the sliced strawberries on top of the mascarpone mixture.", "Repeat the layering process with another layer of dipped ladyfingers and finish with the mascarpone mixture. (Don't add the final layer of strawberries at this point). Cover dish with plastic wrap and refrigerate for at least 12 hours or up to 48 hours.", "Before serving, arrange the remaining half of the sliced strawberries on top of the tiramisu. Dust with powdered sugar."] }
    ],
    nutrition: {
      calories: 394,
      carbs: "55.2g",
      protein: "7.9g",
      fat: "7.9g",
      saturatedFat: "9.5g",
      transFat: "0g",
      cholesterol: "79mg",
      sodium: "237mg",
      potassium: "315mg",
      fiber: "3.2g",
      sugar: "31.5g",
      vitaminD: "0.0mcg",
      calcium: "158mg"
    },
    tags: ["Strawberry", "Tiramisu", "Sweet", "Easy", "Family Favorite"],
    video: "https://www.youtube.com/embed/je_e4ypcNYs?si=O4eQ70_ykCcvePat"
  },
  {
    id: "oreo-tiramisu-trifle",
    name: "Oreo Tiramisu Trifle",
    prepTime: "15 mins",
    cookTime: "0 mins",
    totalTime: "15 mins",
    difficulty: "Easy",
    rating: 4.5,
    reviews: 210,
    image: "../../assets/desserts/Oreo Tiramisu Trifle.webp",
    description: "This dreamy, no-bake Oreo Tiramisu Trifle combines rich flavors with a delightful crunch, making it the perfect dessert for any occasion.",
    ingredients: [
      "20 cookies Oreo cookies, crushed",
      "1 cup heavy cream",
      "1/2 cup mascarpone cheese",
      "1/4 cup powdered sugar",
      "1 tablespoon vanilla extract",
      "1/2 cup brewed coffee, cooled",
      "1 tablespoon cocoa powder (for dusting)",
      "1/4 cup chocolate shavings (for garnish)"
    ],
    instructions: [
      { step: "", details: ["Whip the heavy cream in a mixing bowl until soft peaks form.", "Gently fold in the mascarpone cheese, powdered sugar, and vanilla extract until smooth and fluffy.", "Dip half of the crushed Oreos into the cooled coffee and layer them at the bottom of serving glasses.", "Spread a layer of the mascarpone mixture over the Oreos.", "Repeat the layering process, finishing with a layer of the cream mixture.", "Dust the top with cocoa powder and garnish with chocolate shavings.", "Refrigerate for at least 2 hours before serving."] }
    ],
    nutrition: {
      calories: 140,
      carbs: "21g",
      protein: "1g",
      fat: "6g",
      saturatedFat: "2g",
      transFat: "0g",
      cholesterol: "0mg",
      sodium: "95mg",
      potassium: "40mg",
      fiber: "0.2g",
      sugar: "22g",
      calcium: "0mg",
      iron: "1.2mg"
    },
    tags: ["Dessert", "Oreo", "Easy", "Snack"],
    video: "https://www.youtube.com/embed/60P_1aKONZQ?si=bESOaEtx7QR3wnPp"
  },
  {
    id: "pumpkin-tiramisu",
    name: "Pumpkin Chai Tiramisu",
    prepTime: "20 mins",
    coolingTime: "3 hrs",
    totalTime: "3 hrs 20 mins",
    difficulty: "Easy",
    rating: 5,
    reviews: 201,
    image: "../../assets/desserts/Pumpkin Chai Tiramisu.webp",
    description: "This Pumpkin Chai Tiramisu is a festive fall twist on a classic! Pumpkin pure is whipped into the cream mixture, with chai concentrate used instead of traditional espresso to dip the ladyfingers into. Optionally, you can add a little bit of spiced rum to the chai mixture for a boozy oomph of flavor. This is a great dessert to make for Thanksgiving or other holiday celebrations!",
    ingredients: [
      "1 cup heavy whipping cream",
      "1 cup pumpkin pure",
      "1/3 cup sugar",
      "2 tablespoons maple syrup",
      "8 oz mascarpone cheese",
      "81 cup chai concentrate",
      "2-4 tablespoons spiced rum",
      "2 tablespoons cocoa powder",
      "1 teaspoon pumpkin pie spice",
      "24 ladyfingers",
      "Bittersweet chocolate"
    ],
    instructions: [
      { step: "", details: ["In a medium bowl, whip the 1 cup heavy whipping cream until soft peaks form. In another bowl, beat together the 1 cup pumpkin pure, 1/3 cup sugar, 2 tablespoons maple syrup, and 8 oz. mascarpone cheese until smooth and well combined. Fold the two mixtures together gently until combined.", "In a shallow bowl, mix together the 1 cup chai concentrate and 2-4 tablespoons spiced rum, if using. In a small bowl, mix together the 2 tablespoons cocoa powder and the 1 teaspoon pumpkin pie spice.", "Sift half of the cocoa powder the pumpkin pie spice mix onto the bottom of an 8×8-inch baking dish.", "Dip half of the 24 ladyfingers into the chai concentrate briefly (soaking for too long will result in a soggy texture). Place in a single layer, rounded-side-up, on top of the dusted baking dish. Feel free to break them in half to fit, if needed. Spread half of the pumpkin cream mixture on top. Repeat with the remaining ladyfingers, and the rest of the pumpkin cream mixture.", "Dust the top layer by sifting the remaining half of the cocoa powder and pumpkin pie spice mixture.", "For best results, cover with plastic wrap (or alternative) and refrigerate for at least 3-4 hours, but preferably overnight, or up to 48 hours. Before serving, dust with bittersweet chocolate shavings if desired. Cut into 9 slices (3 slices x3 slices in a square pan) and serve."] }
    ],
    nutrition: {
      calories: 371,
      carbs: "32g",
      protein: "6g",
      fat: "24g",
      saturatedFat: "14g",
      transFat: "0g",
      cholesterol: "120mg",
      sodium: "67mg",
      potassium: "153mg",
      fiber: "2g",
      sugar: "12g",
      vitaminC: "1mg",
      vitaminA: "5142IU",
      calcium: "81mg"
    },
    tags: ["Dessert", "Pumpkin", "Easy", "Everbody's Favorite"]
  },
  {
    id: "panacotta",
    name: "Panacotta",
    prepTime: "15 mins",
    additionalTime: "4 hrs 20 mins",
    totalTime: "4 hrs 35 mins",
    difficulty: "Easy",
    rating: 5,
    reviews: 32,
    image: "../../assets/desserts/Panacotta.png",
    description: "Panna Cotta is that wonderful Italian milk custard, quivering and wobbly with the promise of melting into a flood of creamy goodness in your mouth. Simple yet elegant, perfect for dinner parties.",
    ingredients: [
      "2 1/2 teaspoon gelatine powder",
      "1 1/2 cup milk",
      "1 1/2 teaspoon vanilla bean paste with seeds",
      "1/4 cup caster sugar",
      "1 pinch cooking salt/kosher salt",
      "Oil spray"
    ],
    instructions: [
      { step: "", details: ["Pour the 1/2 cup of milk in a small saucepan, sprinkle the gelatine across the surface then whisk in. Leave for 5 minutes – the gelatine will swell and look curdled.", "Gently warm the gelatine mixture on medium low heat and stir until it melts and looks like lump-free milk again. Don't let it simmer.", "Add the milk, sugar, vanilla bean paste and pinch of salt. Heat just to let the milk warm and stir gently to dissolve the sugar. Don't let the milk simmer or even get steamy or frothy, just gently warm.Once the sugar is dissolved, remove from the heat and leave for 10 minutes to let the vanilla flavour to infuse.", "Stir in cream. Pour into a large jug or bowl, clear glass is best (so you can check for seed sinking later).", "Refrigerate uncovered for 1 hour, stirring at the 30 minute and 45 minute mark, scraping along the sides (in case it starts to set).", "After 1 hour, the mixture should be a pouring cream consistency. Stir, leave for 15 seconds then check the underside to ensure the vanilla beans aren't settling back on the base.", "Lightly oil spray 6 moulds (about 2/3 cup / 160ml each), then lightly wipe out excess. Divide mixture between moulds (if you spy lumps, strain).", "Refrigerate at least 6 hours, preferably overnight. (If not un-moulding, 4 hours is enough)."] },
      { step: "Turning Out Pannacotta", details: ["Remove the Panna Cotta from the fridge. Run the tip of a small knife around the edge of the surface.", "Invert mould onto a plate. Grip the plate and mould with both hands and give it an assertive shake to loosen the Panna Cotta (it might take a few goes).", "Serve the Panna Cotta with additional few berries for color on top."] }
    ],
    nutrition: {
      calories: 253,
      carbs: "13g",
      protein: "5g",
      fat: "21g",
      saturatedFat: "13g",
      transFat: "0g",
      cholesterol: "63mg",
      sodium: "46mg",
      potassium: "139mg",
      fiber: "0g",
      sugar: "13g",
      vitaminC: "0.3mg",
      calcium: "109mg"
    },
    tags: ["Dessert", "Pudding", "Easy", "Everbody's Favorite"],
    video: "https://www.youtube.com/embed/p5mSdmO6kEc?si=HsaszEYKQ9HvQ1ng"
  },
  {
    id: "profiteroles",
    name: "Profiteroles",
    prepTime: "30 mins",
    cookTime: "40 mins",
    totalTime: "1 hr 10 mins",
    difficulty: "Easy",
    rating: 5,
    reviews: 220,
    image: "../../assets/desserts/Profiteroles.png",
    description: "Crispy light-as-air pastry balls filled with custard or cream and topped with chocolate. There are few things in life as delightful as biting into one of these! Terrific lighter / finger food option for dessert.",
    ingredients: [
      "100g / 7 tablespoons unsalted butter",
      "1 cup water",
      "1 cup flour",
      "4 large eggs",
      "Pinch of salt",
      "Vanilla custard (Creme Patissiere)",
      "Ice cream",
      "4 egg yolks",
      "1/4 cup white sugar",
      "3 1/2 tablespoons cornflour/cornstarch",
      "2 1/3 cups milk",
      "1/4 cup extra white sugar",
      "1 teaspoon vanilla bean paste",
      "250g/8oz dark chocolate",
      "1 cup cream"
    ],
    instructions: [
      { step: "", details: ["Place butter in a saucepan over medium heat. When mostly melted, add water then bring to a rapid simmer.", "While liquid is simmering, add flour and pinch of salt, and stir vigorously with a wooden spoon (still on stove) until the dough forms sort of a ball and pulls away from the sides of the saucepan. About 1 minute.", "Remove from heat and let mixture cool for 10 minutes.", "Preheat oven to 220°C/420°F (200°C fan).", "Lightly grease 2 large or 3 standard baking trays with butter, then line with paper. (Grease stops paper sliding)", "Add 1 egg into batter, beat until combined. Add remaining eggs one at a time making sure each is combined before adding the next. Dough should be like a thick paste.", "Place dough into a piping bag fitted with a 13 – 15mm round tip (1/2 – 3/5\").", "Pipe 2 tsp blobs 5cm/2\" apart (I do 16 on each tray). Makes 40 – 50 blobs.", "Wet your finger with water and pat down any peaks to form domes (for nice round balls).", "Bake 2 trays at a time for 15 minutes, switching the trays halfway.", "Remove from oven, reduce heat to 180°C/35°0F (160°C fan). They should be crispy enough that when pierced, they will not collapse – if not, return to oven for 3 minutes.", "Pierce balls with knife then return to oven for 5 – 7 minutes until golden and crispy.", " Transfer to rack, cool fully before filling with custard, cream or split then fill with ice cream. Drizzle with chocolate and serve!"] },
      { step: "Chocolate Topping", details: ["Place cream and chocolate in a heatproof bowl. Microwave 4 x 30 seconds, stirring in between, until incorporated. Cool to warm, then use for drizzling or dipping."] },
      { step: "Custard Topping", details: ["Whisk yolks and sugar, then whisk in cornflour.", "Place milk, vanilla and extra sugar in a saucepan over medium high. Heat until just before simmering.", "Whisk in 1/4 cup hot milk into egg mixture. Whisk in another 1/4 cup. Then add remaining milk mixture and whisk.", "Pour back into saucepan. Return to stove on medium low (low for strong stoves). Whisk constantly 2 to 3 minutes until the mixture thicks to a thick dolloping custard consistency.", "Remove from heat immediately, pour into bowl. Press cling wrap onto surface (stops skin forming) then refrigerate for 4 to 5 hours until set. Do not whisk again once set (loses thickness).", "Spoon into piping bag fitting with a very fine nozzle. Then pipe into profiteroles (use the hole pierced during bake, or make a new hole)."] }
    ],
    nutrition: {
      calories: 101,
      carbs: "8g",
      protein: "1g",
      fat: "6g",
      saturatedFat: "3g",
      transFat: "0g",
      cholesterol: "42mg",
      sodium: "29mg",
      potassium: "60mg",
      fiber: "0g",
      sugar: "4g",
      vitaminC: "0.1mg",
      calcium: "26mg"
    },
    tags: ["Dessert", "Profiteroles", "Pastry", "Easy", "Everbody's Favorite"],
    video: "https://www.youtube.com/embed/63wM3_3J6EM?si=2qTuCtA0PXQmu-_3"
  }
];
