export const filters = [
  { value: 'all', label: 'All' },
  { value: 'recipes', label: 'Recipes & Meal Plans' },
  { value: 'ebooks', label: 'E‑books & Guides' },
  { value: 'printables', label: 'Printables & Stationery' },
];

export const products = [
  {
    id: 'meal-plan-weeknight-7d',
    title: 'Weeknight Meal Plan — 7 Days',
    price: 'Rp 49.000',
    stock: 'Unlimited',
    category: 'recipes',
    meta: 'PDF • 7-day plan • Shopping lists • Subcategory: Weekly Meal Plans',
    img: '/assets/shop/Digital Products/Weeknight Meal Plan 7 Days.png',
    alt: 'Weeknight Meal Plan — 7 Days (PDF)',
    details:
      'Instant download PDF (22 pages) featuring a full week of dinners, timed prep steps, and printable shopping lists. Personal-use license. Best for busy households wanting 30–40 minute meals.',
  },
  {
    id: 'seasonal-menu-summer',
    title: 'Seasonal Menu Pack — Summer',
    price: 'Rp 39.000',
    stock: 'Unlimited',
    category: 'recipes',
    meta: 'PDF • 12 recipes • Subcategory: Seasonal Menus',
    img: '/assets/shop/Digital Products/Seasonal Menu Pack Summer.png',
    alt: 'Seasonal Menu Pack — Summer (PDF)',
    details:
      'PDF pack with 12 fresh seasonal recipes plus substitutions and produce tips. Optimized for in-season ingredients to save cost and boost flavor. Personal use.',
  },
  {
    id: 'diet-plan-vegan-14d',
    title: 'Special Diet Plan — Vegan (14 Days)',
    price: 'Rp 89.000',
    stock: 'Unlimited',
    category: 'recipes',
    meta: 'PDF • 14-day plan • Macros • Subcategory: Special Diet Plans',
    img: '/assets/shop/Digital Products/Special Diet Plan Vegan 14 Days.png',
    alt: 'Special Diet Plan — Vegan 14 Days (PDF)',
    details:
      'Structured 14‑day vegan meal plan (36 pages) with macros, swaps, and batch‑prep guidance. Includes shopping checklists. Personal-use license.',
  },
  {
    id: 'bundle-home-bakery',
    title: 'Baking Bundle — Home Bakery',
    price: 'Rp 99.000',
    stock: 'Unlimited',
    category: 'recipes',
    meta: 'ZIP • 10 recipes + timelines • Subcategory: Baking Bundles',
    img: '/assets/shop/Digital Products/Baking Bundle Home Bakery.png',
    alt: 'Baking Bundle — Home Bakery (ZIP)',
    details:
      'ZIP bundle with 10 detailed recipes (PDF), dough timelines, and troubleshooting notes for consistent results. Great for weekend bakers. Personal-use license.',
  },
  {
    id: 'kids-lunchbox-4w',
    title: 'Kids Lunchbox Meal Plan — 4 Weeks',
    price: 'Rp 79.000',
    stock: 'Unlimited',
    category: 'recipes',
    meta: 'PDF • 20+ ideas • Activity sheets • Subcategory: Kids & Family Menus',
    img: '/assets/shop/Digital Products/Kids Lunchbox Meal Plan 4 Weeks.png',
    alt: 'Kids Lunchbox Meal Plan — 4 Weeks (PDF)',
    details:
      '4‑week planner with balanced lunch ideas, nut‑free swaps, and printable activity sheets. Designed to reduce morning prep time. Personal-use license.',
  },
  {
    id: 'pantry-first-dinners',
    title: 'Pantry-First Dinners Pack',
    price: 'Rp 29.000',
    stock: 'Unlimited',
    category: 'recipes',
    meta: 'PDF • 10 flexible recipes • Subcategory: Pantry-First Recipes',
    img: '/assets/shop/Digital Products/Pantry-First Dinners Pack.png',
    alt: 'Pantry-First Dinners Pack (PDF)',
    details:
      '10 flexible, pantry‑friendly recipes with substitution charts and leftover ideas. Minimal fresh shopping required. Personal-use license.',
  },
  {
    id: 'ebook-one-pot-suppers',
    title: 'One‑Pot Suppers eBook (40 Recipes)',
    price: 'Rp 129.000',
    stock: 'Unlimited',
    category: 'ebooks',
    meta: 'PDF • 120 pages • Subcategory: Themed Cookbooks',
    img: '/assets/shop/Digital Products/One-Pot Suppers eBook (40 Recipes).png',
    alt: 'One-Pot Suppers eBook (PDF)',
    details:
      '120‑page PDF eBook covering soups, braises, and skillet meals with step photos. Includes metric/US measures and freezer notes. Personal-use license.',
  },
  {
    id: 'guide-knife-skills',
    title: 'Knife Skills Illustrated',
    price: 'Rp 59.000',
    stock: 'Unlimited',
    category: 'ebooks',
    meta: 'PDF • 48 pages • Subcategory: Technique Guides',
    img: '/assets/shop/Digital Products/Knife Skills Illustrated.png',
    alt: 'Knife Skills Illustrated (PDF)',
    details:
      '48‑page illustrated PDF with grip, stance, and 12 cuts (dice, julienne, chiffonade). Safety checklist and practice drills included. Personal-use license.',
  },
  {
    id: 'guide-fermentation-beginner',
    title: 'Fermentation for Beginners',
    price: 'Rp 89.000',
    stock: 'Unlimited',
    category: 'ebooks',
    meta: 'PDF • 76 pages • Subcategory: Ingredient Deep‑Dives',
    img: '/assets/shop/Digital Products/Fermentation for Beginners.png',
    alt: 'Fermentation for Beginners (PDF)',
    details:
      'Starter guide to sauerkraut, pickles, and basics of brining. Equipment list, troubleshooting, and food safety notes. PDF, personal-use license.',
  },
  {
    id: 'guide-coffee-brew',
    title: 'Coffee Brew Methods Guide',
    price: 'Rp 45.000',
    stock: 'Unlimited',
    category: 'ebooks',
    meta: 'PDF • 36 pages • Subcategory: Beverage & Cocktail Guides',
    img: '/assets/shop/Digital Products/Coffee Brew Methods Guide.png',
    alt: 'Coffee Brew Methods Guide (PDF)',
    details:
      'Comparative PDF guide for pour‑over, French press, AeroPress, and cold brew. Ratios, grind sizes, and troubleshooting charts. Personal-use license.',
  },
  {
    id: 'guide-food-styling',
    title: 'Food Styling for Home Cooks',
    price: 'Rp 99.000',
    stock: 'Unlimited',
    category: 'ebooks',
    meta: 'PDF • 64 pages • Subcategory: Food Photography & Styling Guides',
    img: '/assets/shop/Digital Products/Food Styling for Home Cooks.png',
    alt: 'Food Styling for Home Cooks (PDF)',
    details:
      'Styling fundamentals for everyday shoots: color, texture, props, and natural light. PDF with step‑by‑step examples. Personal-use license.',
  },
  {
    id: 'ebook-kitchen-stories',
    title: 'Kitchen Stories: Essays',
    price: 'Rp 39.000',
    stock: 'Unlimited',
    category: 'ebooks',
    meta: 'PDF • 88 pages • Subcategory: Chef Interviews & Essays',
    img: '/assets/shop/Digital Products/Kitchen Stories Essays.png',
    alt: 'Kitchen Stories: Essays (PDF)',
    details:
      'A collection of essays and interviews exploring culture and kitchens around the world. PDF, personal-use license.',
  },
  {
    id: 'print-recipe-cards-a6',
    title: 'Printable Recipe Cards (A6) — 24',
    price: 'Rp 25.000',
    stock: 'Unlimited',
    category: 'printables',
    meta: 'PDF • 12 sheets • Subcategory: Recipe Cards',
    img: '/assets/shop/Digital Products/Printable Recipe Cards (A6) 24.png',
    alt: 'Printable Recipe Cards (A6)',
    details:
      'High‑resolution PDF set (12 sheets, 2 cards per sheet). Print on A4/Letter; includes crop marks and bleed. Personal-use license.',
  },
  {
    id: 'print-meal-planner-fridge',
    title: 'Fridge Meal Planner + Grocery Sheet',
    price: 'Rp 29.000',
    stock: 'Unlimited',
    category: 'printables',
    meta: 'PDF • 6 pages • Subcategory: Meal Planners & Grocery Lists',
    img: '/assets/shop/Digital Products/Fridge_Meal_Planner.png',
    alt: 'Fridge Meal Planner + Grocery Sheet',
    details:
      'Printable weekly layout with detachable grocery list. Optimized for magnetic backing or clipboard use. PDF, personal-use license.',
  },
  {
    id: 'print-cheat-sheet-a3',
    title: 'Boiling & Baking Cheat Sheet Poster (A3)',
    price: 'Rp 35.000',
    stock: 'Unlimited',
    category: 'printables',
    meta: 'PDF • A3 print • Subcategory: Posters & Kitchen Art',
    img: '/assets/shop/Digital Products/Boiling & Baking Cheat Sheet Poster (A3).png',
    alt: 'Boiling & Baking Cheat Sheet Poster (A3 PDF)',
    details:
      'One‑page A3 PDF with common temperatures, conversions, and cues. Designed for home printing and easy framing. Personal-use license.',
  },
  {
    id: 'template-dinner-menu',
    title: 'Dinner Party Menu Template (Canva + PDF)',
    price: 'Rp 39.000',
    stock: 'Unlimited',
    category: 'printables',
    meta: 'ZIP • Canva link + PDF • Subcategory: Party Kits / Menu Templates',
    img: '/assets/shop/Digital Products/Dinner Party Menu Template.png',
    alt: 'Dinner Party Menu Template (Canva + PDF)',
    details:
      'ZIP includes a Canva template link and print‑ready PDFs (A4/Letter). Customize fonts/colors to match your event. Personal-use license.',
  },
];