export const saladRecipes = [
  {
    id: "apple-salad",
    name: "Apple Salad",
    prepTime: "20 mins",
    cookTime: "0 mins",
    totalTime: "20 mins",
    difficulty: "Easy",
    rating: 4.5,
    reviews: 350,
    image: "../../assets/salad/Apple Salad.png",
    description: "This apple salad combines sweet tart apples, crunchy pecans, creamy feta, and a zingy maple vinaigrette for the perfect fall side dish. It's ready in just 20 minutes and great for easy weeknight meals or parties!.",
    ingredients: [
      "1 crisp tart apple",
      "8 cups mixed greens or tender lettuces",
      "1/4 cup candied pecanse",
      "1/4 cup feta or goat cheese crumbles",
      "1/4 cup pomegranate seeds or dried cranberries",
      "2 tablespoons maple syrup",
      "2 tablespoons apple cider or white wine vinegar",
      "1 tablespoon Dijon mustard",
      "1/4 teaspoon kosher salt",
      "6 tablespoons olive oil",
      "Fresh ground black pepper"
    ],
    instructions: [
      { step: "", details: ["If using, prepare the candied pecans in advance (or use purchased).", "In a medium bowl, whisk the maple syrup, vinegar, Dijon mustard, salt, and black pepper. Whisk in the olive oil 1 tablespoon at a time until a creamy dressing forms. (If desired, make in advance and refrigerate up to 2 weeks; bring to room temperature prior to serving).", "Thinly slice the apple.", "Place the greens on a large platter or individual plates. Top with apple slices, candied pecans, goat cheese or feta crumbles, and pomegranate seeds or dried cranberries. Top with about 6 tablespoons of the dressing (or more as desired) and serve immediately. (To make ahead, keep all components separate with fresh ingredients and dressing refrigerated. Toss the apples with lemon juice to prevent browning. Bring dressing to room temperature and add all ingredients together directly before serving.)."] }
    ],
    nutrition: {
      calories: 281,
      carbs: "17.9g",
      protein: "2.7g",
      fat: "23.3g",
      saturatedFat: "4.5g",
      transFat: "0g",
      vitaminB6: "0.1mg",
      potassium: "252.8mg",
      fiber: "2.6g"
    },
    tags: ["Salad", "Fruit", "Tart", "Easy", "Vegetarian", "Favorite"],
    video: "https://www.youtube.com/embed/ToFW9CIHaiE?si=P0o1ZEy3LV0p8Wi4"
  },
  {
    id: "butter-lettuce-salad",
    name: "Butter Lettuce Salad",
    prepTime: "5 mins",
    cookTime: "10 mins",
    totalTime: "15 mins",
    difficulty: "Easy",
    rating: 5,
    reviews: 20,
    image: "../../assets/salad/Butter Lettuce Salad.jpg",
    description: "Composed of tender butter lettuce leaves, briny green olives and salty slivers of aged manchego, our butter lettuce salad is a feast for the eyes and the palate.",
    ingredients: [
      "2 tablespoons of salted butter",
      "1/2 cup panko breadcrumbs",
      "2 heads butter lettuce, leaves separated and roughly torn",
      "2 ounces of Manchego cheese, grated",
      "1 cup pitted Castelvetrano olives, halved",
      "1/4 minced chives",
      "Freshly craked black pepper, to taste",
      "1/4 cup unfiltered apple cider vinegar",
      "2 table spoons of honey",
      "2 table spoons of extra-virgin olive oil",
      "1/4 teaspoon of fine sea salt",
      "1/4 teaspoon of freshly craked black pepper"
    ],
    instructions: [
      { step: "", details: ["Make the vinaigrette. In a small bowl, whisk together the vinegar, honey, olive oil, salt, and pepper until smooth. Set aside.", " Toast the breadcrumbs. Melt the butter in a small skillet over medium heat. Once the butter is bubbling, add the panko and cook, stirring frequently, until golden brown and crispy, 3 to 4 minutes. Transfer to a plate and let cool slightly.", "Arrange the lettuce leaves on a large serving platter. Scatter the Manchego, olives, and chives over the top. Season with freshly cracked black pepper.", "Just before serving, drizzle the vinaigrette over the salad and immediately top with the toasted breadcrumbs.", "Serve family-style."] }
    ],
    nutrition: {
      calories: 211,
      carbs: "12g",
      protein: "3g",
      fat: "19g",
      saturatedFat: "0g",
      transFat: "0g",
      cholesterol: "39mg",
      sodium: "268mg",
      potassium: "387.9mg",
      fiber: "1.8g",
      sugar: "1.5g",
      vitaminC: "13mg",
      calcium: "57mg",
      iron: "2mg"
    },
    tags: ["Salad", "Butter", "Breadcrumbs", "Vegetarian"],
    video: "https://www.youtube.com/embed/0PcLfohG4s8?si=uR94TRzLlEExlLz4"
  },
  {
    id: "frisse-salad",
    name: "Frisse Salad",
    prepTime: "20 mins",
    cookTime: "50 mins",
    totalTime: "1 hr 10 mins",
    difficulty: "Easy",
    rating: 4,
    reviews: 19,
    image: "../../assets/salad/Frisee Salad.webp",
    description: "Frisée is a member of the chicory family, along with endive and radicchio. It has curly, frizzy looking leaves with a slightly bitter taste, similar to other chicories. If you can't find frisée but still want to make this salad, you can swap in another chicory, or substitute romaine lettuce or even arugula.",
    ingredients: [
      "2 heads frisée lettuce",
      "1/2 pound slab of bacon",
      "4 eggs",
      "1 tablespoon white wine vinegar",
      "1/4 cup white wine vinegar",
      "1 tablespoon raw honey (or 2 tablespoons brown sugar)",
      "1 tablespoon whole-grain mustard",
      "1/2 cup rendered bacon fat"
    ],
    instructions: [
      { step: "Preparing", details: ["Gather the tools and ingredients for the recipe.", "Place a small pot of water over medium-high heat for the poached eggs. Add the vinegar and let it come to a boil while you are making all the other items. If you have experience making poached eggs, use a larger pot to cook more than 1 at a time. If you have not made them before, start with a small pot. It is much easier.", "Next, wash the lettuce in cold water and either spin it dry with a salad spinner, or pat dry with paper towels or a clean dish towel. When dry, tear it into bite-sized pieces with your hands. Set aside."] },
      { step: "For the Bacon Croutons", details: ["Use a heavy-bottomed pan (preferably cast iron) and heat over medium-high heat. Add the bacon pieces so the broad side is flat against the bottom. When the fat starts to render, lower the heat to medium-low.", "Continue to cook for about 20 minutes, then use tongs to flip the bacon pieces over and cook for another 15 to 20 minutes.", "Use the tongs to remove the crispy bacon bits to a bowl. Leave the fat in the pan."] },
      { step: "Making the Bacon Fat Dressing", details: ["In a small sauté pan, make the gastrique by adding the vinegar and either the honey or brown sugar. Turn the heat to high. Mix well and continue to mix until the vinegar has reduced by about half. Turn the heat to low.", "Add the mustard and mix well.", "Add in about 1/2 cup of the liquid bacon fat. Turn the heat to medium and mix the bacon vinaigrette well. Allow to thicken to your desired consistency. Turn off the heat and make some poached eggs!"] },
      { step: "Making the Poached Eggs", details: ["The water should be nice and hot by now. We are looking for a lazy boil, not a rolling boil. If your water is going crazy, reduce the heat and allow it to calm down. Then, using your slotted spoon, make a slight current in the water with a clockwise motion. Just slight- it should not be crazy. Crack the egg right into the center of the pot. You will see all the wisps rotate around the egg. This is why we created a slight current.", "Allow to cook for 2 minutes for a really runny egg. For a more firm egg, go 2 and a half minutes, or for an even more firm egg, go to 3 minutes. Remove with a slotted spoon and place on a paper towel. Cover with tented foil.", "Cook the remaining eggs in the same manner."] },
      { step: "Plating and Serving", details: ["Add enough dressing to the bottom of a large bowl. Toss in the lettuce and coat using some tongs.", "Place the cooked bacon croutons evenly on the bottom of 4 plates. Top with the dressed frisée and poached egg.", "Serve immediately and enjoy."] }
    ],
    nutrition: {
      calories: 612,
      carbs: "11g",
      protein: "15g",
      fat: "57g",
      saturatedFat: "21g",
      transFat: "0.1g",
      cholesterol: "229mg",
      sodium: "576mg",
      potassium: "663mg",
      fiber: "5g",
      sugar: "5g",
      vitaminA: "6721IU",
      vitaminC: "27mg",
      calcium: "144mg",
      iron: "2mg"
    },
    tags: ["Salad", "Frisee", "Bacon Dressing", "Easy", "Family Favorite"],
    video: "https://www.youtube.com/embed/0K4V1Dkxd7U?si=zyLAfVYHT8JnB7v6"
  },
  {
    id: "italian-salad",
    name: "Italian Salad",
    prepTime: "10 mins",
    cookTime: "5 mins",
    totalTime: "15 mins",
    difficulty: "Easy",
    rating: 4.5,
    reviews: 100,
    image: "../../assets/salad/Italian Salad.png",
    description: "With crisp lettuce, pepperoncini, olives, cherry tomatoes and a zesty homemade dressing, this simple Italian salad recipe is always a crowd-pleaser.",
    ingredients: [
      "2 romaine hearts, roughly chopped",
      "1/2 medium hot onion, thinly sliced",
      "1/2 cup freshly grated, Parmesan chhese, plus more for serving",
      "1 cup peperoncini (whole or sliced, drained)",
      "1/2 cup black olives, whole or sliced",
      "1 pint cherry tomatoes",
      "Freshly cracked black pepper, to taste",
      "2 cups croutons",
      "1 teaspoon garlic powder",
      "1 teaspoon dried oregano",
      "1 teaspoon dried basil",
      "1/2 teaspoon sea salt",
      "1/2 cup extra-virgin olive oil",
      "2 tablespoons red wine vinegar"
    ],
    instructions: [
      { step: "", details: ["Make the dressing. In a jar with a tight fitting lid, combine the garlic powder, oregano, basil, salt, olive oil and red wine vinegar. Shake vigorously until emulsified. ", "Make the salad. In a large salad bowl, combine the Romaine, red onion, Parmesan, peperoncini, olives and tomatoes.", "Season to taste with pepper. Drizzle with the dressing and toss until fully coated. Top with additional parmesan cheese if desired."] }
    ],
    nutrition: {
      calories: 248,
      carbs: "10g",
      protein: "5g",
      fat: "23g",
      saturatedFat: "1g",
      transFat: "0.8g",
      cholesterol: "6mg",
      sodium: "505mg",
      fiber: "3g",
      sugar: "3g",
      iron: "0.02g",
      vitaminC: "1mg"
    },
    tags: ["Salad", "Italian", "Sweet", "Vegetarian", "Easy", "Family Favorite"],
    video: "https://www.youtube.com/embed/OvOyu0VBEiY?si=Zn42ruBnu5bfFabu"
  },
  {
    id: "mediterranean-salad",
    name: "Mediterranean Salad",
    prepTime: "10 mins",
    cookTime: "0 mins",
    totalTime: "10 mins",
    difficulty: "Easy",
    rating: 3.5,
    reviews: 35,
    image: "../../assets//salad/Mediterranean Salad.jpg",
    description: "This Mediterranean salad recipe is as traditional as they come. It's very representative of the regions' agricultural roots and the fresh flavors we continue to love to this day. You can dress it up by adding red onion or toss in feta cheese for a little salty goodness.",
    ingredients: [
      "6 Roma tomatoes, diced",
      "1 large English or hot-house cucumber, diced",
      "1/2 small red onion, thinly sliced, optional",
      "3/4 bunch parsley, leaves and tender stems chopped (about 1/2-3/4 cup chopped leaves)",
      "Kosher salt, to taste",
      "1/2 teaspoon black pepper",
      "1 teaspoon ground Sumac",
      "2 tablespoons extra-virgin olive oil",
      "2 teaspoons freshly squeezed lemon juice, plus more to taste"
    ],
    instructions: [
      { step: "", details: ["In a very large salad bowl, combine the lettuce, cucumber, tomatoes, and parsley. Set aside for 5 minutes or so.", "Pour the olive oil, sumac and lemon juice into a small bowl. Whisk to combine. Drizzle the dressing over the salad, then toss well to coat.", "Add freshly ground black pepper over the salad as a finishing touch."] }
    ],
    nutrition: {
      calories: 66.9,
      carbs: "5.8g",
      protein: "1.2g",
      fat: "4.9g",
      saturatedFat: "0.6g",
      transFat: "0g",
      sodium: "8.6g",
      fiber: "1.4g",
      sugars: "3g"
    },
    tags: ["Salad", "Meditteranian", "Vegetarian", "Easy"],
    video: "https://www.youtube.com/embed/xK8NLldQJDg?si=_UO2qZTsbAtLYOax"
  },
  {
    id: "mexican-salad",
    name: "Mexican Chopped Salad",
    prepTime: "25 mins",
    cookTime: "25 mins",
    totalTime: "50 mins",
    difficulty: "Easy",
    rating: 4,
    reviews: 55,
    image: "../../assets/salad/Mexican Chopped Salad.jpeg",
    description: "This Mexican Chopped Salad might just be the freshest, healthiest, most delicious salad you've ever had the pleasure of meeting. And it's loaded with fabulous Southwestern flavor!",
    ingredients: [
      "1/4 cup fresh lime juice",
      "2 tablespoons honey",
      "1/2 teaspoon cumin",
      "1 clove garlic, finely minced",
      "1/2 teaspoon salt",
      "2 tablespoons canola oil",
      "2 tablespoons extra-virgin olive oil",
      "Freshly ground black pepper",
      "6 6-inch corn tortillas",
      "1 1/2 tablespoons canola oil",
      "1/2 teaspoon sea salt",
      "1 medium head romaine lettuce",
      "1 medium bell pepper",
      "1 medium red onion",
      "1 medium jicama",
      "1 medium zucchini",
      "4 ears corn",
      "1 1/2 cups canned black beans",
      "1/2 cup finely chopped cilantro"
    ],
    instructions: [
      { step: "", details: ["For the dressing, combine lime juice, honey, cumin garlic and salt.", "In a slow, steady stream, add the oils, stirring continuously with a fork or small whisk.", "Taste and add more salt and pepper, if needed. Set aside.", "For the corn tortilla strips, preheat oven to 400˚F.", "Stack corn tortillas on a cutting board. Cut in half. Cut each stack of halves into thin strips, widthwise, about ¼-inch thick.", "Transfer tortilla strips to a sheet pan. Drizzle with oil. Sprinkle with salt and toss to coat.", "Bake for 15-20 minutes, stirring every 5 minutes, or until light golden brown and crisp. Set aside to cool.", "For the salad, place corn, two ears at a time, in the microwave and cook for 3 1/2 minutes.", "Remove from microwave with a hot pad and allow to cool for 5 minutes.", "After cooling, cut bottom end of corn off, about 1 ½ inches from end. Pull back husk and silks (almost all of the silk should easily pull away). Cut kernels from husks and set aside.", "Combine corn and other salad ingredients in a large bowl. Stir to combine. Add dressing and stir to coat all ingredients. Garnish with cilantro leaves, if desired.", "Serve with tortilla strips on top or place a bowl on the side and let guests help themselves."] }
    ],
    nutrition: {
      calories: 228,
      carbs: "35g",
      protein: "5g",
      fat: "8g",
      saturatedFat: "1g",
      transFat: "0g",
      cholesterol: "35g",
      sodium: "438mg",
      potassium: "558mg",
      fiber: "7g",
      sugar: "10g",
      vitaminC: "28.1mg",
      vitaminA: "960IU",
      calcium: "45mg"
    },
    tags: ["Salad", "Mexican", "Tortilla", "Easy", "Vegetarian"],
    video: "https://www.youtube.com/embed/915psklAwGM?si=tolMip7ItQgtyVj_"
  },
  {
    id: "radicchio-salad",
    name: "Radicchio Salad",
    prepTime: "20 mins",
    cookTime: "0 mins",
    totalTime: "20 mins",
    difficulty: "Easy",
    rating: 4.5,
    reviews: 220,
    image: "../../assets/salad/Radicchio Salad.jpg",
    description: "The amazing combination of bitter, sweet and peppery flavors in this radicchio salad recipe will take your idea of a traditional salad to a whole new level. Bright citrus, juicy pears, creamy feta and walnuts plus a simple dressing to pull it all together.",
    ingredients: [
      "1 head radicchio",
      "1 pear, halved and thinly sliced",
      "1 navel orange, peeled and segmented",
      "1 shallot, thinly sliced",
      "1/2 cup walnuts, roughly chopped",
      "1/4 cup feta cheese, crumbled",
      "1 garlic clove, minced",
      "1 lemon, juiced",
      "Kosher salt and black pepper",
      "1 teaspoon sumac",
      "2 tablespoons honey",
      "1/4 cup extra-virgin olive oil"
    ],
    instructions: [
      { step: "", details: ["Core the radicchio and separate the leaves. If you want to make them slightly less bitter you can soak the leaves in cold water for 30 minutes, before drying and assembling the salad.", "Arrange the radicchio leaves on a large platter, then top with orange segments and pear slices. Add the shallots, walnuts, and feta.", "In a small bowl, add the garlic and lemon juice. Season with kosher salt, black pepper, and sumac. Add the honey and whisk. While whisking, drizzle the extra virgin olive oil and continue to whisk until the dressing is well combined.", "Pour the dressing over the radicchio salad and serve."] }
    ],
    nutrition: {
      calories: 343.8,
      carbs: "29.1g",
      protein: "5.6g",
      fat: "25.4g",
      saturatedFat: "8.5g",
      transFat: "0g",
      cholesterol: "8.3mg",
      sodium: "270.8mg",
      fiber: "4.8g",
      sugar: "17.9g",
      calcium: "104.5mg",
      iron: "1.4mg",
      vitaminA: "165.2IU"
    },
    tags: ["Salad", "Radicchio", "Easy", "Vegetarian"],
    video: "https://www.youtube.com/embed/Ok7gmHS_U9s?si=Mfw-ewNSsRudj_pr"
  },
  {
    id: "romaine-salad",
    name: "Romaine Salad with Green Goddess",
    prepTime: "20 mins",
    cookTime: "0 mins",
    totalTime: "20 mins",
    difficulty: "Easy",
    rating: 5,
    reviews: 232,
    image: "../../assets/salad/Romaine Salad with Green Goddess.jpg",
    description: "A simple romaine salad topped with classic green goddess dressing made with mayonnaise, parsley, spinach, basil, tarragon, and lemon juice.",
    ingredients: [
      "1 cup baby spinach",
      "1 cup coarsely chopped fresh flat-leaf parsley",
      "1/3 cup loosely packed fresh basil leaves",
      "3 tablespoons chopped fresh chives",
      "2 tablespoons coarsely chopped tarragon leaves",
      "1/2 medium shallot, peeled, coarsely chopped",
      "1 small garlic clove, peeled and chopped",
      "1/2 teaspoon anchovy paste",
      "1/4 cup fresh lime juice (from 2 medium limes)",
      "6 tablespoons olive oil",
      "1/2 cup mayonnaise",
      "3/4 teaspoon kosher salt",
      "4 cups chopped green cabbage",
      "4 cups chopped hearts of romaine",
      "3 medium Persian cucumbers, sliced",
      "1/2 cup thinly sliced green onions",
      "1 medium ripe avocado, peeled and chopped",
      "1/4 cup chopped roasted, salted pistachios"
    ],
    instructions: [
      { step: "", details: ["Combine spinach, parsley, basil, chives, tarragon, shallot, garlic, anchovy paste, and lime juice in a high-powered blender; blend and slowly add oil through top opening of blender until mixture is smooth, about 1 minute, scraping down sides if needed. Add mayonnaise and salt; blend until smooth. Cover and chill until ready to serve.", "Combine cabbage, romaine, cucumber, and scallions in a large bowl. Add 2/3 cup of the dressing and toss to evenly coat. Divide between 4 bowls and top each bowl with avocado and 1 tablespoon of the pistachios.", "Serve immediately with remaining dressing."] }
    ],
    nutrition: {
      calories: 535,
      carbs: "15g",
      protein: "5g",
      fat: "53g",
      saturatedFat: "8g",
      transFat: "0g",
      cholesterol: "11mg",
      sodium: "648mg",
      potassium: "677mg",
      fiber: "7g",
      sugar: "2.4g",
      vitaminD: "0.0mg",
      calcium: "59mg"
    },
    tags: ["Salad", "Romaine", "Vegetarian", "Easy", "Everbody's Favorite"]
  }
];
